"""Explicit, separately authored checkpoints. Does not modify original task pages."""
import json, math, statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
data={k:[] for k in ['2025-var','2024-host','2023-var','2026-var']}
current=''
def numeric(part,task,label,values,hint,solution):
 fields=[]
 for item in values:
  name,value,*extra=item; unit=extra[0] if extra else ''; tol=extra[1] if len(extra)>1 else .0001
  fields.append(dict(etikett=name,verdi=value,enhet=unit,toleranse=tol))
 add(part,task,label,dict(type='tall',verdier=fields),hint,solution)
def choice(part,task,label,options,correct,hint,solution,multiple=False):
 add(part,task,label,dict(type='valg',flervalg=multiple,alternativer=options,riktige=correct if isinstance(correct,list) else [correct]),hint,solution)
def add(part,task,label,key,hint,solution):
 data[current].append(dict(id=f'{current}-d{part}-q{task}-c{len(data[current])+1}',part=part,task=task,label=label,key=key,hint=hint,solution=solution))
def power_reg(xs,ys):
 lx=list(map(math.log,xs));ly=list(map(math.log,ys));b=sum((x-statistics.mean(lx))*(y-statistics.mean(ly)) for x,y in zip(lx,ly))/sum((x-statistics.mean(lx))**2 for x in lx);return math.exp(statistics.mean(ly)-b*statistics.mean(lx)),b

current='2025-var'
numeric(1,1,'Hvor mange elever er det i klassen?', [('Antall elever',25)],'Finn prosentandelen som ikke deltar.','12 % svarer til 3 elever. Hele klassen har 3 / 0,12 = 25 elever.')
numeric(1,2,'a) Median og gjennomsnitt',[('Median',5),('Gjennomsnitt',5)],'Sorter de ti observasjonene. Gjennomsnitt er summen delt på antallet.','Sortert: 2, 2, 3, 4, 4, 6, 6, 7, 8, 8. Medianen er (4+6)/2 = 5 og gjennomsnittet er 50/10 = 5.')
numeric(1,2,'b) Kumulativ frekvens for 6 personer',[('Kumulativ frekvens',7)],'Tell alle turene med høyst 6 personer.','7 av turene har 6 eller færre personer. Kumulativ frekvens betyr antall til og med den angitte verdien.')
numeric(1,3,'a) Pris per elev når 20 elever blir med',[('Pris',400,'kr')],'Finn den samlede prisen fra et av punktene på grafen.','2 · 4000 = 8000 kroner totalt. 8000 / 20 = 400 kroner per elev. Funksjonen er f(x) = 8000 / x.')
choice(1,4,'Hvilket parti har størst prosentvis framgang?', ['Høyre','Fremskrittspartiet','Like stor framgang'],'Fremskrittspartiet','Sammenlikn økningen med partiets opprinnelige oppslutning.','Høyre: 4 / 24 ≈ 16,7 %. Fremskrittspartiet: 4 / 16 = 25 %. Det siste partiet har størst relativ framgang.')
numeric(1,5,'Fyll inn de fire tallene fra venstre mot høyre i regnestykket.', [('Første faktor',8),('Første eksponent',9),('Andre faktor',2),('Andre eksponent',1)],'Gjør leddet før minustegnet så stort som mulig, og leddet etter så lite som mulig.','8 · 10⁹ − 2 · 10¹ = 7 999 999 980. Eksponenten 9 gir størst første ledd, med 8 som faktor. Av de gjenværende sifrene gir 2 · 10¹ det minste leddet å trekke fra.')
numeric(1,6,'a) Grønne kvadrater i figur 5',[('Antall grønne kvadrater',64)],'Tell rader og kolonner, og trekk fra de hvite rutene.','Figur n har (2n + 1)(n + 2) ruter totalt og 3n − 2 hvite ruter. Grønne ruter: 2n² + 2n + 4. Figur 5 har 64 grønne ruter.')
numeric(1,7,'Kontroller anslagene med klassemidtpunkter og jevn fordeling i medianklassen.', [('Gjennomsnitt',38.1,'år',.11),('Median',35,'år',.1)],'Gjennomsnittet beregnes med klassemidtpunkter. Medianen er ved 50 % av observasjonene.','Gjennomsnitt: (18·20 + 30·40 + 50·30 + 75·10) / 100 = 38,1. Ved jevn fordeling i [20,40) ligger 50 %-punktet på 20 + (50−20)/40·20 = 35 år. Dette er anslag; antakelsene inngår i originaloppgaven.')
numeric(1,8,'Kontroll av programmet: Hvilket år kommer utskriften fram til?', [('År',2030)],'Løkken stopper når matsvinnet ikke lenger er større enn målet.','Programmet ganger matsvinnet med 0,87 hvert år. Etter fem år er det omtrent 79,75 kg, under halvparten av 160 kg. Året er 2030.')
numeric(2,1,'b) og c) Beregn utslippet med modellen som er oppgitt.', [('Tid til halvert samlet utslipp',math.log(.4)/math.log(.95),'år',.1),('Prosentvis reduksjon etter 10 år',(6000-(5000*.95**10+1000))/6000*100,'%',.1)],'Startutslippet er summen fra begge prosessene. Halver dette før du løser likningen.','U(0) = 6000, så halvert utslipp er 3000. 5000·0,95ˣ + 1000 = 3000 gir x ≈ 17,86 år. U(10) ≈ 3993,68 tonn. Nedgangen er (6000−3993,68)/6000·100 ≈ 33,44 %.')
choice(2,1,'e) Kan modellen oppfylle kravet om 800 tonn per år?', ['Ja','Nei'],'Nei','Se på konstantleddet i modellen.','U(x) = 5000·0,95ˣ + 1000 er alltid større enn 1000. Modellen kan derfor ikke nå 800 tonn.')
numeric(2,2,'Antall kronestykker på standardform: a · 10ᵇ. Oppgi a med to desimaler.', [('a',4.85,'',.01),('b',5)],'Gjør høyden om til millimeter før du deler på tykkelsen.','825 m = 825 000 mm. 825 000 / 1,7 ≈ 485 294, altså omtrent 4,85 · 10⁵ kronestykker.')
choice(2,3,'a) Må medianen endres når én person kommer inn?', ['Ja','Nei'],'Nei','Sorter de ti aldrene. Kan den nye personen ha samme alder som den opprinnelige medianen?','De to midterste er 28 og 30, så medianen er 29. Hvis den nye personen er 29 år, blir den midterste verdien blant de elleve 29. Medianen kan altså være uendret.')
choice(2,3,'b) Kan gjennomsnittsalderen bli 30 år med én ny person?', ['Ja','Nei'],'Nei','Regn ut summen av de ti aldrene og sammenlikn med 11 · 30.','Summen er 338. For å få gjennomsnitt 30 med 11 personer måtte den nye personen ha alder 330 − 338 = −8 år. Det er umulig.')
numeric(2,4,'Prisene ved proporsjonal pris og volum',[('4 liter',760,'kr'),('100 ml',19,'kr')],'Finn prisen per milliliter fra flasken på 600 ml.','114 / 600 = 0,19 kr per ml. 4000 ml koster 760 kr, og 100 ml koster 19 kr.')
numeric(2,5,'Kontroller modellen og tiden fram til 17 meter.', [('Vekst per uke',1.28,'m'),('Uker til 17 meter',7.03125,'uker',.05)],'Lengden øker fra 8 til 40 meter i løpet av 25 uker.','L(x) = 8 + 1,28x. Stigningstallet er (40−8)/25 = 1,28. 8 + 1,28x = 17 gir x = 7,03125 uker.')
numeric(2,6,'b) og c) Bruk den oppgitte modellen med vekstfaktor 0,87.', [('Bestand etter 7 år',12000*.87**7,'fugler',1),('År til 35 % reduksjon',math.log(.65)/math.log(.87),'år',.05)],'En reduksjon på 35 % betyr at 65 % står igjen.','F(7) = 12000·0,87⁷ ≈ 4527 fugler. 0,87ˣ = 0,65 gir omtrent 3,09 år.')
numeric(2,7,'Et resultat til presentasjonen: prosentvis endring i antall fødte fra 1983 til 2023.', [('Prosentvis endring',(51980-49937)/49937*100,'%',.1)],'Bruk antall fødte i 1983 som prosentgrunnlag.','(51980−49937) / 49937 · 100 ≈ 4,09 %. Dette er ett mulig resultat; diagrammer og øvrige sammenlikninger vurderes ikke her.')

current='2024-host'
numeric(1,1,'Pris før økningen',[('Pris',40,'kr')],'12 kroner er 30 % av den opprinnelige prisen.','12 / 0,30 = 40 kroner.')
numeric(1,2,'a) Median og gjennomsnitt',[('Median',4.5,'timer'),('Gjennomsnitt',4.2,'timer')],'Sorter observasjonene og summer de ti tallene.','Sortert: 0, 3, 3, 3, 4, 5, 5, 5, 6, 8. Median = (4+5)/2 = 4,5. Gjennomsnitt = 42/10 = 4,2.')
numeric(1,2,'b) Kumulativ frekvens for 5 timer',[('Kumulativ frekvens',8)],'Tell dager med høyst fem arbeidstimer.','8 dager har arbeidstid på 5 timer eller mindre.')
choice(1,3,'Hvilke grafer viser henholdsvis proporsjonalitet og omvendt proporsjonalitet?', ['f er proporsjonal; p er omvendt proporsjonal','g er proporsjonal; q er omvendt proporsjonal','f og g er proporsjonale; p og q er omvendt proporsjonale'],'f er proporsjonal; p er omvendt proporsjonal','En proporsjonal graf er en rett linje gjennom origo. Ved omvendt proporsjonalitet er produktet x·y konstant.','f er en rett linje gjennom origo. På p kan vi lese omtrent (2,400) og (4,200), begge med produkt 800. g går ikke gjennom origo, og q avtar ikke som k/x.')
numeric(1,4,'a) Antall små sirkler',[('Figur 4',24),('Figur 10',48)],'Rammen får fire nye sirkler hver gang. De fire utstikkerne har til sammen åtte sirkler.','Figur n har 4n + 8 sirkler. Figur 4 har 24, og figur 10 har 48.')
numeric(1,5,'Kontroll av programmet: Summen som skrives ut, avrundet til hele tonn.', [('Sum',sum(200*.975**x for x in range(5)),'tonn',1)],'Løkken bruker x = 0, 1, 2, 3 og 4.','Programmet summerer utslippene for fem år, fra 2025 til og med 2029. Summen er omtrent 951 tonn.')
numeric(2,1,'Kontroller modellens salg og prosentøkning.', [('Salg i desember 2025',620*1.045**12,'flasker',1),('Økning til desember 2026',(1.045**24-1)*100,'%',.1)],'Desember 2025 svarer til x = 12 og desember 2026 til x = 24.','Sett x = 12 inn i F. Prosentøkningen over 24 måneder er (1,045²⁴−1)·100. Originaloppgaven ber i tillegg om to framgangsmåter.')
numeric(2,2,'Nedre og øvre anslag for antall bakterier i svampen, målt i milliarder.', [('Nedre anslag',25*150,'milliarder'),('Øvre anslag',54*150,'milliarder')],'Multipliser de to grensene for bakterier per cm³ med volumet.','25·150 = 3750 og 54·150 = 8100 milliarder. På standardform er grensene 3,75·10¹² og 8,1·10¹². Egne anslag mellom grensene er mulige i originaloppgaven.')
choice(2,3,'Gjelder likheten mellom a % av b og b % av a for alle positive a og b?', ['Ja','Nei'],'Ja','Skriv prosentregningen som et produkt delt på 100.','a % av b = ab/100, og b % av a = ba/100. Produktene er like. Husk å begrunne svaret.')
numeric(2,4,'b) Minste og største hele antall parkeringsdager der B er billigst.', [('Minst',100,'dager'),('Høyst',249,'dager')],'Sammenlikn B med både A og C.','1995+30x < 50x gir x > 99,75. 1995+30x < 3490+24x gir x < 249,17. For hele dager er intervallet 100–249.')
numeric(2,5,'a) Median og gjennomsnitt for lag A',[('Median',34.5,'år'),('Gjennomsnitt',40,'år')],'Sorter de seks aldrene og finn summen.','Sortert: 15,18,24,45,60,78. Median = (24+45)/2 = 34,5. Gjennomsnitt = 240/6 = 40. De åpne delene b og c vurderes ikke av disse tallfeltene.')
a,b=power_reg([1,8,22,36,50,64],[10,20,28,33,37,40])
numeric(2,6,'a) Koeffisientene i potensmodellen L(x) = a · xᵇ.', [('a',a,'',.1),('b',b,'',.005)],'Bruk potensregresjon på tabellen. x er antall dager.','Potensregresjon gir omtrent L(x) = 9,9955 · x^0,33367. Små avrundingsforskjeller godtas.')
numeric(2,7,'Et resultat til presentasjonen: prosentvis økning i menns husholdsarbeid fra 1970 til 2010.', [('Økning',(3-2.22)/2.22*100,'%',.1)],'Bruk 2,22 timer som utgangspunkt.','(3,00−2,22)/2,22·100 ≈ 35,1 %. Tabellen bruker desimaltimer, ikke timer og minutter.')
numeric(2,8,'a) og b) Lengde i uke 50 og samlet lengde.', [('Uke 50',40*1.05**49,'km',1),('Til sammen',sum(40*1.05**i for i in range(50)),'km',1)],'Uke 1 har ingen veksttrinn. Uke 50 har 49 veksttrinn.','Uke 50: 40·1,05⁴⁹. Summen er 40 + 40·1,05 + … + 40·1,05⁴⁹, omtrent 8374 km.')

current='2023-var'
choice(1,1,'b) Hvilket påstandsnummer er riktig?', ['1','2','3'],'2','De to kronene sammenliknes hvert år med en større brødpris.','En fast økning på 2 kroner blir en mindre prosent av en stadig høyere pris. Påstand 2 er riktig.')
numeric(1,2,'Hvor mye deig får hver person når 4 personer baker?', [('Deig per person',1.5,'kg')],'Del den samlede deigmengden på antall personer.','6/4 = 1,5 kg. Grafen skal vise sammenhengen y = 6/x. Tegn også grafen på arket.')
numeric(1,3,'b) Antall elever i klassen',[('Antall elever',30)],'Fire elever har ett søsken. Bruk dette sammen med kumulativ og relativ frekvens.','16−4 = 12 elever har to søsken. De utgjør 40 %, så klassen har 12/0,4 = 30 elever.')
numeric(1,4,'a) Antall små sirkler',[('Figur 4',17),('Figur 5',21)],'Tell økningen fra én figur til den neste.','Figurene har 5, 9 og 13 sirkler. Det øker med 4 hver gang. Figur 4 har 17 og figur 5 har 21. Uttrykket er 4n+1.')
numeric(2,1,'Mengde ris på standardform a · 10ᵇ. Bruk tre gjeldende sifre i a.', [('a',2.60,'',.01),('b',12)],'Multipliser befolkning, forbruk per år og antall år.','2,86·10⁹ · 91 · 10 = 2,6026·10¹² kg, som med tre gjeldende sifre blir 2,60·10¹² kg.')
numeric(2,2,'Minste hele antall kopper under kaffeflekken som gir gjennomsnitt større enn fire.', [('Antall kopper',3)],'De elleve synlige tallene har sum 46. Samlet sum må være større enn 12 · 4.','(46+x)/12 > 4 gir x > 2. Minste hele tall er 3. Uten den skjulte verdien kan vi ikke avgjøre om Tores antakelse stemmer.')
choice(2,3,'Er Malins påstand riktig?', ['Ja','Nei'],'Nei','Sammenlikn faktorene 1,07³ og 1/0,93³ med samme mai-pris som utgangspunkt.','1,07³ ≈ 1,225 og 1/0,93³ ≈ 1,243. Faktorene er ulike, så påstanden er feil.')
numeric(2,4,'Et resultat til presentasjonen: andelen syklister med hjelm i hele uka.', [('Andel',41/63*100,'%',.1)],'Summer begge kolonnene før du beregner prosenten.','41 av 63 syklister har hjelm, omtrent 65,1 %. Et uvektet gjennomsnitt av dagsprosentene gir ikke nødvendigvis denne andelen.')
numeric(2,5,'a) Gjennomsnittslønn med klassemidtpunkter, avrundet til hele kroner.', [('Gjennomsnitt',83975/146*1000,'kr',1)],'Multipliser hvert klassemidtpunkt med frekvensen og divider summen med antall ansatte.','De vektede klassemidtpunktene summerer til 83 975 tusen kroner for 146 ansatte. Gjennomsnittet er omtrent 575 171 kroner. Dette er et anslag basert på klassemidtpunkter.')
numeric(2,6,'b) og c) Beløpet i mai og samlet beløp etter den opprinnelige planen.', [('Mai',1600*1.045**9,'kr',1),('Totalt',sum(1600*1.045**x for x in range(10)),'kr',1)],'Mai svarer til x = 9. For totalen må du ta med alle månedene fra x = 0 til x = 9.','P(9) ≈ 2377,75 kr. Samlet beløp er omtrent 19 661 kr, mindre enn målet på 25 000 kr.')
a,b=power_reg([1,5,8,10,12,15,18,20],[2060,5770,7795,8992,10105,11656,13099,14000])
numeric(2,7,'a) Potensmodellen P(x) = a · xᵇ',[('a',a,'',1),('b',b,'',.002)],'Bruk potensregresjon med ukenummer som x.','Potensregresjon gir omtrent a = 2060,23 og b = 0,6399. Modellen kan avrundes til P(x) = 2060·x^0,64.')

current='2026-var'
numeric(1,1,'Antall brune egg',[('Brune egg',1040)],'20 % er en femtedel.','5200 · 0,20 = 1040 brune egg.')
numeric(1,2,'a) Median, gjennomsnitt, variasjonsbredde og typetall',[('Median',5.5),('Gjennomsnitt',8.3),('Variasjonsbredde',29),('Typetall',6)],'Sorter tallene. Variasjonsbredde er største minus minste verdi.','Sortert: 1,1,3,5,5,6,6,6,20,30. Median = 5,5, gjennomsnitt = 83/10 = 8,3, variasjonsbredde = 30−1 = 29, typetall = 6.')
numeric(1,2,'b) Relativ frekvens for 6 vogner, oppgitt i prosent',[('Relativ frekvens',30,'%')],'Tell hvor mange av de ti togene som har akkurat seks vogner.','3 av 10 tog har seks vogner. Det er 30 %.')
numeric(1,3,'Fyll inn de manglende verdiene fra tabellen.', [('Prosentendring ved faktor 1,4',40,'%'),('Vekstfaktor ved +17,5 %',1.175),('Vekstfaktor ved −28 %',.72),('Prosentendring ved faktor 0,67',-33,'%'),('Prosentendring ved faktor 2',100,'%')],'Vekstfaktor er 1 pluss prosentendringen delt på 100.','1,4 gir +40 %. +17,5 % gir 1,175. −28 % gir 0,72. 0,67 gir −33 %. 2 gir +100 %.')
choice(1,4,'Koster varen mer, mindre eller det samme som før?', ['Mer','Mindre','Det samme'],'Mindre','Multipliser de to vekstfaktorene.','0,8·1,2 = 0,96. Prisen er 96 % av den opprinnelige, altså 4 % lavere.')
choice(1,5,'Hvilke tre prisendringer beskriver nevneren?', ['Én økning på 5 % og to nedganger på 15 %','Én nedgang på 5 % og to økninger på 15 %','Én økning på 5 % og én nedgang på 30 %'],'Én økning på 5 % og to nedganger på 15 %','Tolk hver vekstfaktor og eksponenten.','1,05 er en økning på 5 %. 0,85² er to nedganger på 15 %. Uttrykket finner den gamle prisen ved å dele dagens pris på produktet av faktorene. Rekkefølgen av endringene kan ikke bestemmes fra produktet.')
numeric(1,6,'a) Prosentpoeng og b) prosentvis nedgang',[('Prosentpoeng',.54),('Prosentvis nedgang',9,'%')],'Forskjellen er 6−5,46. Den relative nedgangen beregnes med 6 som grunnlag.','Forskjellen er 0,54 prosentpoeng. 0,54/6·100 = 9 %.')
numeric(1,7,'Resultatet av regnestykket',[('Svar',75)],'3 millioner ganger 0,000025 kan forenkles med tierpotenser.','3 000 000 · 0,000025 = 75.')
numeric(1,8,'Hva er verdien av √64?', [('Verdi',8)],'Finn det ikke-negative tallet som ganget med seg selv gir 64.','8·8 = 64, så √64 = 8. Den fullstendige sorteringen må du fortsatt gjøre på arket.')
choice(1,9,'a) Hvilken sammenheng gjelder når matutgiften også tas med?', ['Proporsjonal','Omvendt proporsjonal','Ingen av delene'],'Ingen av delene','Prisen per elev er 15000/x + 250. Undersøk om produktet x·P(x) er konstant.','P(x) = 15000/x + 250. Tillegget på 250 gjør at sammenhengen verken er proporsjonal eller omvendt proporsjonal.')
numeric(1,10,'Antall grønne sirkler',[('Figur 5',23),('Figur 10',43)],'Hver ny figur får én ny sirkel i hver av tre rader og én i halen.','Figurene har 7,11,15,19 sirkler. Antallet er 4n+3. Figur 5 har 23 og figur 10 har 43.')
numeric(1,11,'Pris ved proporsjonal pris og vekt',[('1,4 kg',168,'kr'),('250 g',30,'kr')],'Gjør gram om til kilogram.','1,4·120 = 168 kroner. 250 g = 0,25 kg, så prisen blir 30 kroner.')
choice(1,12,'Hva forteller verdien programmet skriver ut?', ['Gjennomsnittet av tallene i listen','Medianen av tallene i listen','Summen av tallene i listen'],'Gjennomsnittet av tallene i listen','Programmet deler summen på antall tall.','Listen har sum 50 og fem tall. Programmet regner ut 50/5 = 10, gjennomsnittet.')
numeric(1,13,'b) Anslag for medianalder ved jevn fordeling i intervallet 20–30 år.', [('Medianalder',26.6666667,'år',.5)],'Finn hvor grafen når 50 %. Den går fra 30 % til 60 % mellom 20 og 30 år.','20 + (50−30)/(60−30)·10 ≈ 26,7 år. Vi antar jevn fordeling i intervallet; grafen gir et anslag, ikke den eksakte medianen.')
numeric(2,1,'b) Årlig prosentvis reduksjon i den oppgitte modellen.', [('Reduksjon',11,'%')],'Vekstfaktoren i den oppgitte modellen er 0,89.','1−0,89 = 0,11, altså 11 % per år. Modellen bruker en avrundet vekstfaktor for halvering over seks år.')
numeric(2,2,'b) Åpent intervall der standardmedlemskap er billigst. Oppgi grensene; selve grensene gir lik pris med et annet medlemskap.', [('Nedre grense',5,'timer'),('Øvre grense',17.5,'timer')],'Sammenlikn 300+40x med både 150+70x og 1000.','Standard er billigere enn basis når x > 5, og billigere enn premium når x < 17,5. Intervallet er 5 < x < 17,5.')
numeric(2,3,'a) Gjennomsnitt og median, og b) kumulativ frekvens for 5 fraværsdager.', [('Gjennomsnitt',3,'dager'),('Median',1,'dag'),('Kumulativ frekvens',13)],'Summer de femten verdiene, sorter dem, og tell alle verdier som er høyst fem.','Summen er 45 og antallet 15, så gjennomsnittet er 3. Den åttende sorterte verdien er 1. Det er 13 verdier på 5 eller mindre.')
choice(2,3,'d) Må kumulativ frekvens for 5 fraværsdager være høyere i bedrift B?', ['Ja','Nei'],'Nei','Høyere median og lavere standardavvik bestemmer ikke alene denne kumulative frekvensen.','Nei. Et moteksempel for B er ni 2-ere, tre 3-ere og tre 6-ere. De har gjennomsnitt 3, median 2 og lavere standardavvik enn A, men bare 12 verdier er høyst 5. A har 13.')
numeric(2,4,'Et resultat til presentasjonen: økningen i andelen som får dagens første nyheter på smarttelefon, fra 2019 til 2025.', [('Økning i prosentpoeng',18),('Prosentvis økning',56.25,'%',.1)],'Tabellen går fra 32 % til 50 %. Skill mellom prosentpoeng og relativ økning.','50−32 = 18 prosentpoeng. Relativ økning er 18/32·100 = 56,25 %. Bruk resultatet i presentasjonen din.')

(ROOT/'docs/past-exam-checks.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print({k:len(v) for k,v in data.items()})
