"""Append the September 2026 collection; never rewrite existing questions."""
import json, math, statistics
from decimal import Decimal, ROUND_HALF_UP
def round(value, ndigits=None):
    result=Decimal(str(value)).quantize(Decimal(1).scaleb(-(ndigits or 0)), rounding=ROUND_HALF_UP)
    return int(result) if ndigits is None else float(result)
from pathlib import Path
from collections import Counter
ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT/'public/oppgaver-2027.json'
M = lambda s: r'\('+str(s)+r'\)'
def n(x): return format(x,'.10g').replace('.',',')
def clean(x):
    if isinstance(x,float): return float(format(x,'.12g'))
    if isinstance(x,list): return [clean(v) for v in x]
    if isinstance(x,dict): return {k:clean(v) for k,v in x.items()}
    return x
new=[]; groups=[]
def numeric(values, labels=None, units=None, tol=0):
    if not isinstance(values,list): values=[values]
    return {'type':'tall' if len(values)==1 else 'flere_tall','verdier':[{'verdi':v,'etikett':(labels or ['Svar'])[i],'enhet':(units or ['']*len(values))[i],'toleranse':tol} for i,v in enumerate(values)]}
def choice(options,right,i):
    opts=options[i%len(options):]+options[:i%len(options)]
    return {'type':'valg','flervalg':False,'alternativer':opts,'riktige':[options[right]]}
def add(part,family,i,theme,level,text,key,known,method,setup,solution,feedback,check,vis=None,group=None):
    hints=([f'Hva vet vi? {known}',method,setup] if part==1 else [method,setup])
    q={'id':f'2py27-{516+len(new):03}','del':part,'tema':theme,'deltema':family.replace('-','_'),'ferdighet':['beregne' if key['type']!='valg' else 'begrunne','tolke'],'niva':level,'hjelpemidler':'uten' if part==1 else 'med','sporsmal':text,'hint':hints,'svar':solution,'fasit':key,'variantfamilie':f'utvidelse-d{part}-{family}', 'kontroll':{'operasjon':'utvidelse_2026_09','metode':family,'inndata':check},'laeringsstotte':{'feil':feedback},'nivabegrunnelse':{1:'Kjent metode brukes direkte på oppgitte data.',2:'Eleven må knytte sammen opplysninger og velge riktig grunnlag eller representasjon.',3:'Eleven må håndtere flere vilkår eller velge en løsning under samtidige begrensninger.'}[level]}
    if vis:q['visualisering']=vis
    if group:q['oppgavegruppe']=group
    new.append(clean(q))
def table(headers,rows):return {'type':'tabell','kolonner':headers,'rader':rows}
items=['en tursekk','en hjelm','en sovepose','en arbeidsjakke','en verktøykasse','en regnjakke','en lampe','en koffert','en stol','en høyttaler']
activities=['klatrekurs','sykkelkurs','svømmekurs','dansekurs','skikurs','padlekurs','tegnekurs','fotokurs','sykurs','matkurs']
# Twenty distinct Del 1 families, ten numerically checked variants each.
for i in range(10):
    missing=4+2*i; total=missing*5
    add(1,'fravaerende-andel',i,'prosent',2,f'På et {activities[i]} møter 80 % av de påmeldte. {missing} personer møter ikke. Hvor mange var påmeldt?',numeric(total,units=['personer']),f'80 % møter, mens {missing} personer ikke møter. Alle påmeldte utgjør hele gruppen. Vi skal finne antallet før fraværet trekkes fra.', 'Finn først prosentdelen som ikke møter. De fraværende er resten av hele gruppen, så trekk oppmøteprosenten fra 100 %.',f'Andelen som mangler er 100 − 80 prosent. Sett opp {M(str(missing)+r"\cdot100/(100-80)")} for å finne hele gruppen.',f'De fraværende er 20 %. Hele gruppen er fem ganger så stor: {missing} · 5 = {total} personer.','Tallet som er oppgitt gjelder dem som ikke møter. Finn deres andel før du regner tilbake til hele gruppen.',{'missing':missing,'attendance':80})
    price=400+80*i
    add(1,'ulikt-sammenlikningsgrunnlag',i,'prosent',2,f'Butikk A selger {items[i]} for {price} kroner. Butikk B tar 25 % mer. Hvor mange prosent billigere er varen hos A enn hos B?',numeric(20,units=['%']),f'A tar {price} kroner, og påslaget hos B regnes av prisen hos A. Spørsmålet bruker derimot prisen hos B som sammenlikningsgrunnlag.','Tenk at A sin pris består av fire like deler. B sin pris får én slik del i tillegg. Forskjellen er den samme i kroner begge veier.',f'Finn B sin pris med {M(str(price)+r"\cdot125/100")}. Del deretter prisforskjellen på prisen hos B og gang med 100.',f'B tar {price*5//4} kroner. Forskjellen er {price//4} kroner. Relativt til B er dette {price//4}/{price*5//4} · 100 = 20 %.','Når du spør hvor mye billigere A er enn B, er B sin pris hele sammenlikningsgrunnlaget.',{'a':price,'markup':25})
    p=[10,20,25,40,50,10,20,25,40,50][i]; start=100*(i+2)
    f=(1-p/100)*(1+p/100)
    add(1,'to-motsatte-endringer',i,'prosent',2,f'Prisen på {items[i]} er {start} kroner. Den settes først ned {p} % og deretter opp {p} % av den nye prisen. Bestem samlet vekstfaktor.',numeric(f),f'Startprisen er {start} kroner. Begge endringene er {p} %, men økningen regnes av den reduserte prisen. Vi trenger faktoren for hele forløpet.','Gjør hver prosentendring om til et tall du ganger med. Ved nedgang trekker du prosentdelen fra én; ved oppgang legger du den til én.',f'Sett opp produktet {M(f"(1-{p}/100)(1+{p}/100)")}. Regn ut begge parentesene før du ganger; prosentene skal ikke bare strykes.',f'Samlet faktor er {n(1-p/100)} · {n(1+p/100)} = {n(f)}. Påslaget regnes av et lavere beløp enn rabatten.', 'Hver endring har sitt eget prosentgrunnlag. Gang faktorene sammen for å beskrive sluttpris delt på startpris.',{'p':p})
    a=10+5*i; delta=a//5
    add(1,'andel-og-prosentpoeng',i,'prosent',2,f'I konstruerte øvingsdata øker andelen som sykler til skolen fra {a} % til {a+delta} %. Angi økningen i prosentpoeng og den prosentvise økningen.',numeric([delta,20],['Økning i prosentpoeng','Prosentvis økning'],['prosentpoeng','%']),f'Andelen starter på {a} % og ender på {a+delta} %. Vi skal beskrive endringen på to ulike måter, og må holde de to svarfeltene fra hverandre.','Prosentpoeng finner du ved å trekke prosenttallene fra hverandre. Prosentvis økning sammenlikner denne forskjellen med den opprinnelige andelen.',f'Bruk {M(f"{a+delta}-{a}")} i første felt. I andre felt bruker du forskjellen delt på {a} og ganger med 100. Samme differanse inngår i begge.',f'Forskjellen er {delta} prosentpoeng. Prosentvis økning er {delta}/{a} · 100 = 20 %.','Prosentpoeng er differansen. Prosentvis økning bruker startandelen som nevner.',{'a':a,'b':a+delta})
    micro=12+2*i; count=3+i
    add(1,'standardform-enheter',i,'potenser',2,f'Én komponent har masse {micro} milligram. En pakke inneholder {count} millioner komponenter. Angi samlet masse i kilogram. 1 kilogram = 1 000 000 milligram.',numeric(micro*count,units=['kg']),f'Hver komponent veier {micro} milligram, og det er {count} millioner komponenter. Omregningen til kilogram er gitt, så alle nødvendige enheter er kjent.','Gang massen per komponent med antallet. Del deretter antallet milligram på antallet milligram i ett kilogram. Millionfaktorene kan forkortes.',f'Sett opp {M(f"{micro}\\cdot({count}\\cdot10^6)/10^6")}. Forkort de like tierpotensene før du ganger tallene som står igjen.',f'Massen er {micro} · {count} millioner milligram. Deling på én million gir {micro*count} kg.','Kontroller at du har omregnet både antallet komponenter og masseenheten, ikke bare flyttet desimaltegnet én gang.',{'mg':micro,'millions':count})
    a=5+i;b=2+i
    add(1,'rot-og-potens',i,'potenser',1,f'Regn ut {M(f"\\sqrt{{{a*a}}}+{b}^2")}.',numeric(a+b*b),f'Uttrykket inneholder kvadratroten av {a*a} og en potens med grunntall {b}. Regneartene må utføres før resultatene legges sammen.','Finn først det ikke-negative tallet som ganget med seg selv gir tallet under rottegnet. Regn deretter potensen som grunntallet ganget med seg selv.',f'Skriv regningen som {M(f"\\sqrt{{{a*a}}}+{b}\\cdot{b}")}. Rottegnet gjelder bare første ledd; summen skal ikke settes under ett rottegn.',f'Kvadratroten er {a}, og {b}² = {b*b}. Summen blir {a+b*b}.','Kvadratroten og andre potens er ulike operasjoner. Utfør dem hver for seg før addisjonen.',{'a':a,'b':b})
    a=3+i;b=2+i
    add(1,'eksponent-i-kvotient',i,'potenser',2,f'Finn eksponenten k slik at {M(f"10^{{{a}}}\\cdot10^{{{b}}}/10^2=10^k")}.',numeric(a+b-2),f'Alle potensene har grunntall 10. Eksponentene i telleren er {a} og {b}, og nevneren er 10 i andre. Bare den samlede eksponenten skal leveres.','Ved multiplikasjon med samme grunntall legger du sammen eksponentene. Ved divisjon trekker du nevnerens eksponent fra tellerens eksponent.',f'Sett opp {M(f"k={a}+{b}-2")}. Regn på eksponentene i denne rekkefølgen uten å skrive ut de store tierpotensene som vanlige tall.',f'Potensreglene gir k = {a} + {b} − 2 = {a+b-2}.','Grunntallet er fortsatt 10. Svaret er eksponenten, ikke selve det store tallet.',{'a':a,'b':b,'denominator':2})
    kg=2+i; rate=30+10*i
    add(1,'proporsjonal-oppskrift',i,'proporsjonalitet',2,f'Til {kg} kg bær brukes {kg*rate} gram sukker. Samme blandingsforhold skal brukes til {kg+2} kg bær. Hvor mange gram sukker trengs?',numeric((kg+2)*rate,units=['g']),f'{kg} kg bær trenger {kg*rate} gram sukker. Mengden bær øker til {kg+2} kg, mens forholdet mellom bær og sukker skal være det samme.','Finn sukkermengden som hører til ett kilogram bær ved å dele. Den mengden kan du så bruke flere ganger for den nye bærmengden.',f'Sett opp {M(f"({kg*rate}/{kg})\\cdot{kg+2}")}. Første parentes gir gram per kilogram, og gangingen gir gram for hele den nye blandingen.',f'Forholdet er {kg*rate}/{kg} = {rate} g per kg. Det trengs {rate} · {kg+2} = {(kg+2)*rate} g.','Samme blandingsforhold betyr at sukkermengde delt på bærmengde er konstant.',{'kg':kg,'sugar':kg*rate,'newkg':kg+2})
    rent=1200+240*i; food=40+10*i
    add(1,'omvendt-med-fastledd',i,'proporsjonalitet',2,f'En hytte koster {rent} kroner å leie. Leien deles likt mellom x personer, og hver betaler {food} kroner for mat i tillegg. x er et positivt heltall. Fyll inn a og b i {M("P(x)=a/x+b")}, der P er kroner per person.',numeric([rent,food],['a','b'],['kr','kr']),f'Hele hytteleien er {rent} kroner, mens maten koster {food} kroner for hver deltaker. Det er bare hytteleien som skal deles mellom x personer.','Skill en samlet kostnad fra en kostnad per deltaker. Den samlede kostnaden må deles på antallet; den personlige kostnaden legges til etterpå.',f'Sammenlikn {M("P(x)=a/x+b")} med beskrivelsen. Leddet med deling skal være personens andel av leien, mens tillegget gjelder hver enkelt.',f'P(x) = {rent}/x + {food}. Dermed er a = {rent} og b = {food}. Mattillegget gjør at hele prisen ikke er omvendt proporsjonal med x.','Leien deles mellom alle. Matprisen er allerede oppgitt per person og skal ikke deles på x.',{'rent':rent,'food':food})
    a=20+5*i;b=80+10*i
    add(1,'lineaer-fra-to-priser',i,'lineaere_funksjoner',2,f'Leie av utstyr koster {2*a+b} kroner for to timer og {6*a+b} kroner for seks timer. Prisen følger {M("P(x)=ax+b")}, der x er timer. Finn a og b.',numeric([a,b],['a: timepris','b: fast avgift'],['kr/time','kr']),f'To timer koster {2*a+b} kroner og seks timer koster {6*a+b} kroner. Modellen har samme prisøkning per time, men kan også ha en fast avgift.','Finn prisforskjellen mellom de to leietidene og del på forskjellen i timer. Da får du timeprisen. Bruk så en av prisene til å finne avgiften.',f'Start med {M(f"a=({6*a+b}-{2*a+b})/(6-2)")}. Når a er funnet, trekker du betaling for to timer fra totalprisen for to timer.',f'a = ({6*a+b} − {2*a+b})/4 = {a}. Deretter b = {2*a+b} − 2 · {a} = {b}.','Bruk endring i pris delt på endring i tid. Totalpris delt på timer inkluderer også den faste avgiften.',{'a':a,'b':b,'x':[2,6]})
    fixed=60+10*i;rate=15+5*i;limit=7+i;budget=fixed+rate*limit+rate//2
    add(1,'budsjett-heltall',i,'variabler',2,f'Et verksted tar {fixed} kroner i fast avgift og {rate} kroner per merke som trykkes. Du kan bruke høyst {budget} kroner. Hvor mange merker kan du maksimalt bestille?',numeric(limit,units=['merker']),f'Budsjettet er {budget} kroner. Før trykking betales en fast avgift på {fixed} kroner, og hvert merke koster deretter {rate} kroner. Antallet må være helt.', 'Trekk den faste avgiften fra budsjettet først. Finn hvor mange ganger stykkprisen får plass i resten. Du kan ikke bestille en del av et merke.',f'Bruk ulikheten {M(f"{fixed}+{rate}x\\le {budget}")}. Kontroller det største mulige heltallet ved å beregne totalprisen, også for ett merke til.',f'{limit} merker koster {fixed+rate*limit} kroner. {limit+1} koster {fixed+rate*(limit+1)}, som er over budsjettet. Maksimum er {limit}.','Et desimalsvar må rundes ned når du skal holde deg innenfor et budsjett og kjøpe hele merker.',{'fixed':fixed,'rate':rate,'budget':budget})
    k=2+i; extra=3+i
    add(1,'rektangulaert-rutemonster',i,'variabler_og_monstre',2,f'Et rutemønster bygges slik: Trinn n har n rader, hver med n + {k} ruter, og {extra} løse ruter utenfor rektangelet. Finn a, b og c i {M("R(n)=an^2+bn+c")} for totalt antall ruter.',numeric([1,k,extra],['a','b','c']),f'Det er n rader, og hver rad har n + {k} ruter. I tillegg kommer {extra} løse ruter. Regelen beskriver alle trinn, ikke bare de første viste antallene.', 'Antall ruter i rektangelet er antall rader ganget med antall ruter i hver rad. De løse rutene legges til etter at dette produktet er regnet ut.',f'Start med {M(f"n(n+{k})+{extra}")}. Gang n inn i parentesen og sammenlikn leddene med andregradsleddet, førstegradsleddet og konstantleddet.',f'R(n) = n(n + {k}) + {extra} = n² + {k}n + {extra}. Koeffisientene er 1, {k} og {extra}.','Gang antall rader med antall ruter per rad før du legger til rutene som ligger utenfor.',{'k':k,'extra':extra})
    start=7+2*i; step=3+i; term=9+i
    add(1,'tilvekst-og-startnummer',i,'variabler_og_monstre',2,f'En tribune har {start} seter på rad 1. Hver neste rad har {step} flere seter enn raden foran. Hvor mange seter er det på rad {term}?',numeric(start+(term-1)*step,units=['seter']),f'Rad 1 starter med {start} seter. Hver gang radnummeret øker, kommer {step} nye seter til. Vi skal finne antallet på rad {term}, ikke totalt på tribunen.','Tell hvor mange overganger det er fra første rad til raden du skal finne. Antall økninger er én mindre enn radnummeret siden første rad allerede er med.',f'Bruk {M(f"{start}+({term}-1)\\cdot{step}")}. Regn ut antall økninger først, gang med tilveksten og legg til setene på første rad.',f'Det er {term-1} økninger. Antallet er {start} + {term-1} · {step} = {start+(term-1)*step} seter.','Startverdien gjelder rad 1. Derfor er det én færre økning enn radnummeret.',{'start':start,'step':step,'term':term})
    mean=8+i;known=[mean-4,mean-2,mean+1,mean+2];last=5*mean-sum(known)
    add(1,'manglende-observasjon',i,'statistikk',2,f'Fem elever leste i gjennomsnitt {mean} sider. Fire av sidetallene er {", ".join(map(str,known))}. Hvor mange sider leste den siste eleven? Dette er konstruerte øvingsdata.',numeric(last,units=['sider']),f'Gjennomsnittet er {mean} sider for fem elever. Vi kjenner fire sidetall og skal finne det siste. Gjennomsnittet gjelder alle fem, også eleven med ukjent sidetall.','Finn samlet sidetall ved å gange gjennomsnitt med antall elever. Legg deretter sammen de fire kjente tallene, og finn det som mangler i totalsummen.',f'Sett opp {M(f"5\\cdot{mean}-({'+'.join(map(str,known))})")}. Parentesen samler de kjente sidetallene før de trekkes fra hele summen.',f'Summen må være {5*mean}. Kjente tall summerer til {sum(known)}. Siste elev leste {last} sider.','Gjennomsnitt ganger antall gir totalsummen. Trekk fra alle de kjente observasjonene.',{'mean':mean,'known':known})
    base=5+i; values=[base-3,base-1,base,base+1,base+3];newlast=base+13
    add(1,'ekstremverdi-sentralmaal',i,'statistikk',2,f'Konstruerte målinger i minutter er {", ".join(map(str,values))}. Den største målingen korrigeres til {newlast}. Finn nytt gjennomsnitt og ny median.',numeric([base+2,base],['Nytt gjennomsnitt','Ny median'],['min','min']),f'Listen har fem målinger. Bare den største, {values[-1]}, erstattes av {newlast}. De andre målingene beholder verdiene sine, og antallet er fortsatt det samme.','Se først hvor mye totalsummen endres. Fordel denne endringen på alle observasjonene for gjennomsnittet. Medianen finnes ved å sortere den korrigerte listen.',f'Bruk {M(f"({'+'.join(map(str,values[:-1]))}+{newlast})/5")} for gjennomsnittet. Finn deretter den midterste plassen uten å blande de to sentralmålene.',f'Ny sum er {5*(base+2)}, så gjennomsnittet er {base+2}. Den tredje verdien er fortsatt {base}, som er medianen.','En endring i største måling påvirker summen, men trenger ikke flytte den midterste verdien.',{'before':values,'newlast':newlast})
    freq=[2+i,4+i,3+i,1+i];total=sum(freq)
    add(1,'kumulativ-antall',i,'statistikk',1,'Tabellen viser konstruerte øvingsdata for antall bøker lest. Hvor mange elever leste høyst to bøker?',numeric(sum(freq[:3]),units=['elever']),'Tabellen oppgir hvor mange elever som har hvert bokantall. «Høyst to» tar med dem som leste færre bøker også, ikke bare akkurat to.','Finn radene der bokantallet er mindre enn eller lik grensen. Summer frekvensene i disse radene; raden over grensen skal ikke tas med.',f'Sett opp {M("+".join(map(str,freq[:3])))}. Det er elevantallene i frekvenskolonnen som legges sammen, ikke bokantallene i første kolonne.',f'Antallet er {" + ".join(map(str,freq[:3]))} = {sum(freq[:3])} elever.','Høyst to betyr null, én eller to. Kumulativ frekvens summerer alle disse antallene.',{'freq':freq},table(['Bøker','Elever'],[[j,v] for j,v in enumerate(freq)]))
    offset=2*i;freq=[2,4,4];bounds=[offset,offset+10,offset+20,offset+30];avg=offset+17
    add(1,'klassemidtpunkt-anslag',i,'statistikk',2,'Tabellen viser konstruerte reisetider. Anslå gjennomsnittet i minutter ved å bruke klassemidtpunkter.',numeric(avg,units=['min']),f'Tidene er samlet i tre intervaller med henholdsvis {freq[0]}, {freq[1]} og {freq[2]} observasjoner. Vi kjenner intervallene, men ikke hver enkelt reisetid.','Finn midtpunktet mellom grensene i hvert intervall. Gang hvert midtpunkt med intervallets frekvens, slik at intervaller med flere observasjoner teller mer.',f'Første midtpunkt er {M(f"({bounds[0]}+{bounds[1]})/2")}. Summer de vektede bidragene fra alle intervallene og del på samlet antall observasjoner.',f'Midtpunktene er {offset+5}, {offset+15}, {offset+25}. Vektet sum er {avg*10}; delt på 10 blir anslaget {avg} minutter.','Et gjennomsnitt av bare midtpunktene ignorerer at intervallene inneholder ulike antall observasjoner.',{'bounds':bounds,'freq':freq},table(['Reisetid (min)','Antall'],[[f'[{bounds[j]}, {bounds[j+1]})',v] for j,v in enumerate(freq)]))
    values=[3+i,7+i,4+i,9+i];threshold=5+i;code=f'tall = {values}\ntotal = 0\nfor x in tall:\n    if x > {threshold}:\n        total = total + x\nprint(total)';answer=sum(v for v in values if v>threshold)
    add(1,'kode-betinget-sum',i,'programmering',2,'Hva skriver programmet ut? Tallene er konstruerte målinger. Lever tallet som vises etter løkken.',numeric(answer),f'Listen inneholder {", ".join(map(str,values))}, og total starter på null. Bare tall som er større enn {threshold} legges til, og print står etter hele løkken.','Gå gjennom listen i den rekkefølgen den er skrevet. Test hvert tall mot grensen før du endrer totalen. Et tall som ikke passer vilkåret, gir ingen endring.',f'Skriv en kladdelinje for hver observasjon: {M("\\text{ny total}=\\text{gammel total}+x")} brukes bare når testen er sann. Les totalen etter siste observasjon.',f'Bare {values[1]} og {values[3]} er større enn {threshold}. Programmet skriver ut summen {answer}.','Løkken besøker alle tallene, men if-testen bestemmer hvilke som blir lagt til totalen.',{'values':values,'threshold':threshold}, {'type':'programkode','kode':code})
    start=4+i;step=3+i;rounds=3
    code=f'antall = {start}\nfor runde in range({rounds}):\n    antall = antall + {step}\nprint(antall)'
    opts=['Antallet etter tre like store tillegg.','Summen av alle mellomverdiene.','Antall ganger løkken gjentas.','Startantallet før første tillegg.']
    add(1,'kode-tolkning-tillegg',i,'programmering',1,'Velg én beskrivelse av tallet programmet skriver ut.',choice(opts,0,i),f'Antall starter på {start}. Inne i løkken legges {step} til den gamle verdien, og print-linjen står utenfor løkken. Vi skal tolke det som blir vist.','Se hvilken variabel som endres, og om koden samler flere verdier i en egen sum. Plasseringen av print avgjør når den lagrede verdien leses av.','Lag en oversikt med en linje før løkken og en linje etter hver gjennomgang. Sammenlikn hva den siste linjen beskriver med innholdet i svaralternativene.',f'Variabelen økes tre ganger med {step}, fra {start} til {start+3*step}. Print viser antallet etter tilleggene, ikke summen av mellomverdiene.','Print står etter løkken. Følg verdien som lagres i antall; koden har ingen egen variabel som summerer mellomverdiene.',{'start':start,'step':step,'rounds':rounds},{'type':'programkode','kode':code})
    a=4+i
    opts=[f'{a}, {a}, {a}',f'{a-2}, {a}, {a+2}',f'{a-1}, {a}, {a+1}']
    add(1,'samme-gjennomsnitt-spredning',i,'statistikk_og_samfunn',2,f'Tre lag har målinger med samme gjennomsnitt, {a}. Velg datasettet som har variasjonsbredde null. Dataene er konstruerte.',choice(opts,0,i),f'Alle lag har samme gjennomsnitt, {a}. Spørsmålet handler om variasjonsbredde, som måler avstanden mellom største og minste måling i hvert lag.','Undersøk ytterverdiene i hvert alternativ hver for seg. Lik plassering av gjennomsnittet betyr ikke at målingene ligger like tett rundt det.','Bruk regelen variasjonsbredde = største måling − minste måling på hvert av alternativene. Finn hvilket datasett som har helt sammenfallende ytterverdier.',f'Listen {opts[0]} har største og minste verdi {a}. Forskjellen er null. De to andre listene har variasjonsbredde 4 og 2.','Samme gjennomsnitt betyr ikke samme spredning. Variasjonsbredde null krever at alle målingene er like.',{'options':[ [a,a,a],[a-2,a,a+2],[a-1,a,a+1] ]})
assert len(new)==200
# Ten cases with four independent submissions, then sixteen standalone families.
for i in range(10):
    a=6000+500*i;c=1200+100*i;b=0.88+i*.005;years=4+i%3
    gid=f'd2-utvidelse-energi-{i+1:02}'
    groups.append({'id':gid,'del':2,'tittel':f'Energibruk i bygg {i+1}','innledning':f'Konstruerte øvingsdata: Årlig energibruk i et bygg beskrives av {M(f"E(t)={a}\\cdot{n(b)}^t+{c}")} kWh per år. t er antall år etter tiltaket, med t = 0 ved start. Modellen brukes for 0 ≤ t ≤ 15, og t kan være et desimaltall. Den konstante delen beskriver utstyr som skal brukes som før.','data':{}})
    def g(j):return {'id':gid,'deloppgave':'abcd'[j],'rekkefolge':j+1}
    add(2,'energi-startverdi',i,'funksjoner_og_modeller',1,'Bestem det årlige energiforbruket ved start, i kWh per år.',numeric(a+c,units=['kWh/år']),'','Sett t lik null i hele uttrykket. Husk at den konstante delen kommer i tillegg til den delen som endres.',f'Bruk {M(f"E(0)={a}\\cdot{n(b)}^0+{c}")}. Et positivt tall opphøyd i null er én.',f'E(0) = {a} + {c} = {a+c} kWh per år. Startverdien omfatter begge delene.','Startverdien er hele uttrykket ved t = 0, også konstantleddet.',{'a':a,'b':b,'c':c},group=g(0))
    value=a*b**years+c
    add(2,'energi-modellverdi',i,'funksjoner_og_modeller',1,f'Bruk modellen i innledningen til å beregne årlig energiforbruk etter {years} år. Avrund til nærmeste hele kWh per år.',numeric(value,units=['kWh/år'],tol=.5),'','Sett inn antall år som eksponent. Regn ut potensen før du ganger med koeffisienten og legger til den konstante delen.',f'Skriv {M(f"{a}\\cdot{n(b)}^{{{years}}}+{c}")} i beregningsverktøyet. Behold desimalene fram til siste avrunding.',f'E({years}) = {n(value)} kWh per år, som avrundes til {round(value)} kWh per år.','Den konstante delen skal legges til etter vekstberegningen. Den skal ikke ganges med vekstfaktoren.',{'a':a,'b':b,'c':c,'years':years},group=g(1))
    avg=(value-a-c)/years
    add(2,'energi-gjennomsnittlig-vekstfart',i,'funksjoner_og_modeller',2,f'Finn gjennomsnittlig vekstfart for det årlige energiforbruket fra t = 0 til t = {years}, med modellen i innledningen. Oppgi fortegn og avrund til én desimal. Enhet: (kWh per år) per år.',numeric(avg,units=['(kWh/år)/år'],tol=.05),'','Gjennomsnittlig vekstfart bruker forskjellen mellom sluttverdi og startverdi, delt på lengden av tidsintervallet.',f'Bruk {M(f"(E({years})-E(0))/{years}")}. Regn modellverdiene direkte uten å bruke avrundede svar fra andre deloppgaver.',f'({n(value)} − {a+c})/{years} = {n(avg)}. Avrundet vekstfart er {n(round(avg,1))} (kWh per år) per år. Negativt fortegn betyr nedgang.','Sluttverdi minus startverdi gir negativt tall ved nedgang. Bruk uavrundede verdier fra modellen.',{'a':a,'b':b,'c':c,'years':years},group=g(2))
    floor=c-200
    options=[f'Nei, den variable delen er positiv og den konstante delen er {c}.',f'Ja, samme prosentnedgang gjør hele forbruket mindre enn {floor}.',f'Ja, konstantleddet må også ganges med {n(b)} hvert år.']
    add(2,'energi-modellbegrensning',i,'funksjoner_og_modeller',2,f'Kan modellen gi et årlig forbruk under {floor} kWh per år i det oppgitte tidsintervallet? Velg én konklusjon med begrunnelse.',choice(options,0,i),'','Skill mellom den delen som avtar og den delen som ikke endres. Undersøk hvilket fortegn potensleddet har for tillatte tider.','Tenk på hva som skjer når potensleddet blir lite. Kontroller om det kan trekke totalen under verdien av konstantleddet.',f'Nei. {a} · {n(b)} opphøyd i t er positivt. Totalen er derfor større enn {c}, som igjen er større enn {floor}.','En positiv del lagt til en konstant gir alltid en total over konstanten. Den konstante delen avtar ikke.',{'a':a,'b':b,'c':c,'floor':floor},group=g(3))
for i in range(10):
    start=800+70*i;factor=1.06+.005*i;limit=start*(1.5+.02*i);t=0
    while start*factor**t<=limit:t+=1
    add(2,'foerste-hele-periode',i,'prosent',2,f'Et verksteds ukentlige produksjon følger {M(f"P(t)={start}\\cdot{n(factor)}^t")}, der t er hele uker etter start og P er antall deler per uke. Modellen gjelder de første 20 ukene. Hva er første hele uke der produksjonen ifølge modellen er større enn {n(limit)} deler per uke?',numeric(t,units=['uker']),'','Lag en verditabell for hele uker, eller løs ulikheten med et digitalt verktøy. Spørsmålet gjelder strengt større enn grensen.','Kontroller både uken du vil svare og uken rett før. Et avrundet tidspunkt fra en kontinuerlig modell kan havne på feil side av grensen.',f'P({t-1}) = {n(start*factor**(t-1))}, mens P({t}) = {n(start*factor**t)}. Første hele uke over grensen er {t}.','Prøv heltallige uker. Svaret må være over grensen, mens forrige uke skal være på eller under den.',{'start':start,'factor':factor,'limit':limit})
    start=1200+100*i;years=3+i%4;factor=1.035+.005*i;end=start*factor**years
    add(2,'finne-aarlig-vekst',i,'prosent',2,f'Et verksted øker produksjonen fra {start} til {n(round(end,3))} enheter per uke over {years} år. Anta samme prosentvise vekst hvert år. Bestem årlig prosentvis vekst, avrundet til én desimal.',numeric(((round(end,3)/start)**(1/years)-1)*100,units=['%'],tol=.05),'','La b være årlig vekstfaktor. Etter flere år er det startverdien ganget med b én gang for hvert år som skal gi sluttverdien.',f'Løs {M(f"{start}\\cdot b^{{{years}}}={n(round(end,3))}")} for positiv b. Gjør deretter vekstfaktoren om til prosentvis økning.',f'b = ({n(round(end,3))}/{start}) opphøyd i 1/{years}. Årlig vekst er (b − 1) · 100, som avrundes til {n(round((factor-1)*100,1))} %.','Samlet prosentøkning delt på antall år tar ikke hensyn til at prosentgrunnlaget endres hvert år.',{'start':start,'end':round(end,3),'years':years})
    rate=40+5*i;fixed=rate*4;flat=rate*(10+i);lo=9;hi=2*(10+i)-9
    add(2,'tre-avtaler-intervall',i,'lineaere_funksjoner',3,f'En aktivitet har tre månedsavtaler. A: {rate} kr per besøk. B: {fixed} kr fast og {n(rate/2)} kr per besøk. C: {flat} kr uansett antall besøk. Finn minste og største heltallige antall besøk der B er strengt billigere enn både A og C.',numeric([lo,hi],['Minste antall besøk','Største antall besøk'],['besøk','besøk']),'','Skriv en prisfunksjon for hver avtale. B må tilfredsstille to ulike sammenlikninger samtidig; ett skjæringspunkt alene er ikke nok.','Løs B(x) < A(x) og B(x) < C(x). Finn heltallene i overlappen, og kontroller at like priser ved endepunkter ikke blir tatt med.',f'B < A krever x > 8. B < C krever x < {2*(10+i)-8}. Dermed er alle heltall fra {lo} til {hi} gyldige, inkludert disse grensene.','Strengt billigere utelukker lik pris. Ta bare med antall besøk som oppfyller begge ulikhetene.',{'rate':rate,'fixed':fixed,'flat':flat})
    a=12+i;b=60+3*i;xs=[0,1,2,3,4];ys=[b+a*x+e for x,e in zip(xs,[2,-1,-2,-1,2])]
    add(2,'lineaer-regresjon-data',i,'funksjoner_og_modeller',2,'Tabellen viser konstruerte data for tidsbruk ved pakking. Finn modellen T(x) = ax + b med lineær minste kvadraters regresjon. x er antall pakker og T er sekunder. Oppgi a og b med én desimal.',numeric([a,b],['a','b'],['s/pakke','s'],tol=.05),'','Legg inn antall pakker som x-verdier og sekunder som y-verdier. Bruk lineær regresjon som minimerer summen av kvadrerte loddrette avvik.','Les av begge koeffisientene fra den tilpassede modellen. Linjen skal bruke alle målingene, ikke bare gå gjennom første og siste punkt.',f'Regresjonen gir T(x) = {a}x + {b}. Avvikene er 2, −1, −2, −1 og 2 sekunder; de summerer til null og har null vektet sum mot x.','Regresjon tilpasser en linje til alle punktene. Konstantleddet trenger ikke være første måling.',{'x':xs,'y':ys},table(['Pakker x','Tid (s)'],list(map(list,zip(xs,ys)))))
    a=150+10*i;b=1.08+.005*i;xs=[0,2,4,6,8];ys=[round(a*b**x) for x in xs]
    logs=[math.log(y) for y in ys];slope=sum((x-4)*(y-statistics.mean(logs)) for x,y in zip(xs,logs))/40;aa=math.exp(statistics.mean(logs)-4*slope);bb=math.exp(slope)
    add(2,'eksponentialregresjon-data',i,'funksjoner_og_modeller',2,'Tabellen viser konstruerte medlemstall. x er år etter start. Finn M(x) = a · b opphøyd i x ved lineær minste kvadraters regresjon av ln(M) mot x. Oppgi a med én desimal og b med tre desimaler.',{'type':'flere_tall','verdier':[{'verdi':aa,'etikett':'a','toleranse':.05},{'verdi':bb,'etikett':'b','toleranse':.0005}]},'','Regn den naturlige logaritmen av hvert medlemstall. Tilpass deretter en rett linje til x og de logaritmerte verdiene.','Hvis ln(M) = u + vx, er a = exp(u) og b = exp(v). Bruk alle målepunktene og vent med avrunding til koeffisientene er funnet.',f'Tilpasningen gir a = {n(aa)} og b = {n(bb)}. Avrundede koeffisienter er {n(round(aa,1))} og {n(round(bb,3))}.','Kontroller at regresjonen er utført på logaritmerte medlemstall. Ikke bruk vanlig lineær regresjon direkte på M.',{'x':xs,'y':ys},table(['År x','Medlemmer M'],list(map(list,zip(xs,ys)))))
    exponent=[.5,1.5,2,2.5,3,.5,1.5,2,2.5,3][i];mult=2+i%3;change=(mult**exponent-1)*100
    add(2,'potensmodell-relativ-endring',i,'funksjoner_og_modeller',2,f'I en modell er energibehovet {M(f"E(v)={2+i}\\cdot v^{{{n(exponent)}}}")}, der v > 0 er fart i m/s og E er energienheter. Farten ganges med {mult}. Hvor mange prosent øker energibehovet ifølge modellen? Avrund til én desimal.',numeric(change,units=['%'],tol=.05),'','Sammenlikn energibehovet ved den nye og den gamle farten. Koeffisienten foran potensen og den gamle farten forkortes i forholdet.',f'Finn først endringsfaktoren {M(f"{mult}^{{{n(exponent)}}}")}. Trekk fra én og gang med 100 for å få prosentvis økning.',f'Forholdet E({mult}v)/E(v) = {mult} opphøyd i {n(exponent)} = {n(mult**exponent)}. Økningen er {n(round(change,1))} %.','Farten endres med en faktor. I en potensmodell må denne faktoren opphøyes i eksponenten før prosentendringen beregnes.',{'exponent':exponent,'multiplier':mult})
    na=12+i;nb=20+2*i;ma=18+i;mb=24+i;mean=(na*ma+nb*mb)/(na+nb)
    add(2,'vektet-gjennomsnitt-grupper',i,'statistikk',2,f'Konstruerte øvingsdata: Gruppe A har {na} elever og gjennomsnittlig reisetid {ma} minutter. Gruppe B har {nb} elever og gjennomsnitt {mb} minutter. Finn gjennomsnittet for alle elevene samlet, avrundet til én desimal.',numeric(mean,units=['min'],tol=.05),'','Finn samlet reisetid i hver gruppe ved å gange gruppestørrelse med gruppens gjennomsnitt. Gruppene skal telle etter antall elever.','Legg sammen begge gruppenes totale reisetid og del på samlet elevantall. Vent med avrunding til du har regnet denne kvotienten.',f'({na} · {ma} + {nb} · {mb})/({na} + {nb}) = {n(mean)}. Samlet gjennomsnitt er {n(round(mean,1))} minutter.','Et vanlig gjennomsnitt av de to gruppemidlene gir gruppene lik vekt. Her er gruppestørrelsene forskjellige.',{'na':na,'nb':nb,'ma':ma,'mb':mb})
    values=[2+i,4+i,5+i,5+i,8+i,12+2*i];sd=statistics.pstdev(values);mean=statistics.mean(values)
    add(2,'populasjonsstandardavvik',i,'statistikk',1,f'Konstruerte ventetider i minutter: {", ".join(map(str,values))}. Finn populasjonsstandardavviket for hele dette datasettet. Avrund til to desimaler.',numeric(sd,units=['min'],tol=.005),'','Legg alle observasjonene inn i et statistikkverktøy. Velg populasjonsstandardavvik, som bruker antall observasjoner som nevner.','Ved egen beregning finner du først gjennomsnittet. Kvadrer avvikene, finn gjennomsnittet av kvadratene og ta kvadratroten til slutt.',f'Gjennomsnittet er {n(mean)}. Variansen er {n(sd*sd)}, og kvadratroten gir standardavvik {n(round(sd,2))} minutter.','Utvalgsstandardavvik bruker én mindre i nevneren. Oppgaven ber om populasjonsstandardavvik for alle de oppgitte målingene.',{'values':values})
    freqs=[10+2*i,30+3*i,40+4*i,20+2*i];bounds=[0,5,15,35,60];heights=[freqs[j]/(bounds[j+1]-bounds[j]) for j in range(4)]
    add(2,'histogram-hoeyder',i,'representasjoner',2,'Tabellen viser konstruerte ventetider. Et histogram skal ha søyleareal lik antall observasjoner. Angi høyden for hvert intervall, i observasjoner per minutt. Avrund til to desimaler.',numeric(heights,[f'Høyde [{bounds[j]}, {bounds[j+1]})' for j in range(4)],['obs/min']*4,tol=.005),'','Intervallene har ulike bredder. For at arealene skal representere antall, må du dele hver frekvens på bredden til akkurat det intervallet.','Finn først intervallbredde som øvre grense minus nedre grense. Bruk så høyde = frekvens/bredde for hver rad, i samme rekkefølge som svarfeltene.',f'Intervallbreddene er 5, 10, 20 og 25 minutter. Høydene er {", ".join(n(round(h,2)) for h in heights)} observasjoner per minutt.','Søylehøyde alene kan ikke vise antall når intervallene har ulik bredde. Antallet skal svare til høyde ganger bredde.',{'bounds':bounds,'freq':freqs},table(['Ventetid (min)','Antall'],[[f'[{bounds[j]}, {bounds[j+1]})',v] for j,v in enumerate(freqs)]))
    offset=i;bounds=[offset,offset+10,offset+20,offset+40];freq=[10+i,30+i,20+i];N=sum(freq);med=offset+10+(N/2-freq[0])/freq[1]*10
    add(2,'median-interpolasjon',i,'statistikk',2,'Tabellen viser konstruerte reisetider. Anslå medianen ved lineær interpolasjon ved 50 % av observasjonene. Anta jevn fordeling innenfor hvert intervall. Avrund til én desimal i minutter.',numeric(med,units=['min'],tol=.05),'','Summer frekvensene og finn halvparten av totalen. Finn intervallet der den kumulative frekvensen passerer denne posisjonen.','Finn hvor stor andel av medianintervallets observasjoner som trengs etter de foregående intervallene. Bruk samme andel av intervallbredden og legg til nedre grense.',f'Halvparten av {N} er {n(N/2)}. Anslaget blir {offset+10} + ({n(N/2)} − {freq[0]})/{freq[1]} · 10 = {n(round(med,1))} minutter. Det bygger på fordelingsantakelsen.','Bruk frekvensen i medianintervallet når du finner andelen inne i intervallet, ikke totalt antall observasjoner.',{'bounds':bounds,'freq':freq},table(['Reisetid (min)','Antall'],[[f'[{bounds[j]}, {bounds[j+1]})',v] for j,v in enumerate(freq)]))
    mean=6+i;median=5+i;values=[median-3,median-1,median,median,median+3,median+7]
    key=numeric(values,[f'Tall {j+1}' for j in range(6)]);key.update({'konstruksjon':'datasett','vilkaar':{'antall':6,'gjennomsnitt':mean,'median':median,'minimum':0,'heltall':True}})
    add(2,'konstruere-datasett',i,'statistikk',3,f'Konstruer seks ikke-negative heltall med gjennomsnitt {mean} og median {median}. Skriv ett tall i hvert felt. Tallene kan leveres i hvilken rekkefølge som helst, og like tall er tillatt.',key,'','Gjennomsnittet bestemmer summen av alle tallene. Med et partall observasjoner bestemmes medianen av de to midterste verdiene etter sortering.','Velg først to midterste verdier som gir ønsket median. Plasser så mindre eller like tall før dem og større eller like tall etter dem; juster totalsummen uten å flytte medianen.',f'Ett mulig svar er {", ".join(map(str,values))}. Summen er {6*mean}, så gjennomsnittet er {mean}. De to midterste verdiene er begge {median}. Alle lister som oppfyller kravene godtas.','Kontroller både totalsummen og de to midterste verdiene i den sorterte listen. Alle seks tall må være ikke-negative heltall.',{'mean':mean,'median':median,'count':6})
    old=180+10*i;newusage=old*.85;people0=40+i;people1=people0+8;relative=((newusage/people1)/(old/people0)-1)*100
    add(2,'forbruk-per-person',i,'proporsjonalitet',2,f'Konstruerte øvingsdata: Et bygg bruker først {old} liter vann per dag med {people0} brukere. Forbruket faller med 15 %, mens antall brukere øker til {people1}. Hvor mange prosent avtar vannforbruket per bruker? Oppgi et positivt tall med én desimal.',numeric(-relative,units=['%'],tol=.05),'','Finn først nytt totalforbruk. Del gammelt og nytt forbruk på hvert sitt brukerantall for å sammenlikne liter per bruker.','Regn nedgang i forbruk per bruker som gammel verdi minus ny verdi, delt på gammel verdi, ganger 100. Oppgaven ber om størrelsen på nedgangen.',f'Før: {old}/{people0} = {n(old/people0)} liter per bruker. Etter: {n(newusage)}/{people1} = {n(newusage/people1)}. Nedgangen er {n(round(-relative,1))} %.','Både totalforbruk og antall brukere endres. Finn to verdier per bruker før du beregner prosentnedgangen.',{'old':old,'factor':.85,'people0':people0,'people1':people1})
    old=90+2*i;newindex=120+3*i;growth=(newindex/old-1)*100
    add(2,'indeks-nytt-grunnlag',i,'statistikk_og_samfunn',2,f'En prisindeks er {old} i år A og {newindex} i år B. Begge indeksene bruker samme basisår. Hvor mange prosent økte prisen fra A til B? Avrund til én desimal.',numeric(growth,units=['%'],tol=.05),'','Indeksene har felles basis og kan sammenliknes med et forhold. Spørsmålet har år A som start, selv om dette ikke er indeksens basisår.','Del forskjellen mellom indeksene på indeksen i år A og gang med 100. Differansen alene er endring i indekspoeng.',f'Prisøkningen er ({newindex} − {old})/{old} · 100 = {n(round(growth,1))} %.','Bruk indeksen i år A som nevner når veksten skal måles fra A til B.',{'old':old,'new':newindex})
    visits=1000+200*i;loans=visits*2;newvis=visits*1.2;newloans=loans*1.1
    options=['Besøk økte mer i prosent enn utlån.','Utlån per besøk økte.','Antall forskjellige besøkende økte nødvendigvis.','Lengre åpningstid var årsaken til økningen.']
    add(2,'data-konklusjon',i,'statistikk_og_samfunn',2,f'Konstruerte bibliotekdata: Besøk økte fra {visits} til {round(newvis)} og utlån fra {loans} til {round(newloans)}. Velg den ene påstanden som følger av disse opplysningene.',choice(options,0,i),'','Sammenlikn prosentendringene med hvert sitt starttall. Skill mellom antall besøk og antall ulike personer som har vært innom.','Regn også utlån per besøk før og etter. Opplysningene viser endringer i registrerte antall, men inneholder ingen undersøkelse av årsakene.',f'Besøk økte med 20 %, utlån med 10 %. Dermed økte besøk mest i prosent. Utlån per besøk falt, og personantall og årsak kan ikke bestemmes.','Et besøk er ikke nødvendigvis en ny person. Tallene beskriver utvikling, men dokumenterer ikke årsak.',{'visits':[visits,newvis],'loans':[loans,newloans]})
    deposit=300+50*i;rate=.02+.002*i;years=4+i%4;balance=0
    for _ in range(years):balance=(balance+deposit)*(1+rate)
    code=f'saldo = 0\nfor aar in range({years}):\n    saldo = saldo + {deposit}\n    saldo = saldo * {n(1+rate).replace(",",".")}\nprint(round(saldo, 2))'
    add(2,'sparing-innskudd-foer-rente',i,'programmering',2,f'I en forenklet sparemodell settes {deposit} kroner inn ved starten av hvert år. Hele saldoen får deretter {n(rate*100)} % rente ved årets slutt. Ingen gebyrer eller uttak. Hva skriver programmet ut etter {years} år? Oppgi kroner med to desimaler.',numeric(balance,units=['kr'],tol=.005),'','Legg merke til rekkefølgen inne i løkken: først nytt innskudd, så rente på hele saldoen. Første innskudd får dermed rente allerede første år.','Følg saldoen år for år eller kjør koden. Ikke avrund saldoen underveis; print avrunder først etter at alle år er gjennomført.',f'Saldoen følger regelen ny saldo = (gammel saldo + {deposit}) · {n(1+rate)}. Etter {years} år er saldoen {n(balance)}; utskriften er {n(round(balance,2))} kroner.','Et innskudd ved starten av året får rente samme år. Kontroller også at antall innskudd er lik antall runder.',{'deposit':deposit,'rate':rate,'years':years},{'type':'programkode','kode':code})
    start=1600+100*i;factor=.84+.005*i;limit=700+30*i;value=start;rounds=0
    while value>limit:value*=factor;rounds+=1
    code=f'verdi = {start}\naar = 0\nwhile verdi > {limit}:\n    verdi = verdi * {n(factor).replace(",",".")}\n    aar = aar + 1\nprint(aar)'
    add(2,'kode-terskel-tolkning',i,'programmering',2,'Programmet undersøker en verdi som avtar én gang per år. Hvor mange år skriver det ut? Bruk hele år og følg testen nøyaktig.',numeric(rounds,units=['år']),'','While-testen sjekkes før hver gjennomgang. Verdien endres og årstelleren øker bare når den nåværende verdien fortsatt er over grensen.','Lag en tabell med år og verdi, eller kjør koden. Finn den første raden som gjør while-testen usann, og les av årstelleren på den raden.',f'Etter {rounds-1} år er verdien {n(start*factor**(rounds-1))}, og etter {rounds} år {n(value)}. Da er testen usann. Programmet skriver ut {rounds}.','Løkken stopper når verdien er mindre enn eller lik grensen. Årstelleren viser gjennomførte endringer.',{'start':start,'factor':factor,'limit':limit},{'type':'programkode','kode':code})
assert len(new)==400
# Carry explicit scoring and review metadata; preserve every existing object.
for q in new:
    key=q['fasit']; labels=key.get('verdier',[])
    for v in labels:
        if v['toleranse']>0:v['avrunding']={.5:0,.05:1,.005:2,.0005:3}[v['toleranse']]
    q['kontroll']['svarfelt']=[{'id':f"{q['id']}-felt-{j+1}",'etikett':v['etikett'],'enhet':v.get('enhet',''),'toleranse':v['toleranse'],'maks_poeng':1} for j,v in enumerate(labels)]
    q['kontroll']['poengregel']='Ett poeng per korrekt tallfelt. Enkeltvalg: ett poeng for riktig alternativ, ellers null. Konstruksjon: ett poeng for riktig gjennomsnitt og ett for riktig median; antall, heltall og nedre grense må være oppfylt. Ingen minuspoeng.'
    q['kontroll']['visning']='Hint og begreper åpnes på forespørsel. Tilbakemelding etter gyldig innsending gjelder bare denne oppgaven. Full løsning åpnes etter innsending; ved riktig svar vises løsningen automatisk.'
SKILLS={
'fravaerende-andel':['finne_helhet','prosent_av_komplement'],
'ulikt-sammenlikningsgrunnlag':['velge_prosentgrunnlag','sammenlikne_priser'],
' to-motsatte-endringer':['kombinere_vekstfaktorer','tolke_prosentforloep'],
'andel-og-prosentpoeng':['beregne_prosentpoeng','beregne_relativ_endring'],
'standardform-enheter':['regne_med_tierpotenser','omregne_masse'],
'rot-og-potens':['beregne_kvadratrot','regnerekkefolge'],
'eksponent-i-kvotient':['bruke_potensregler','finne_eksponent'],
'proporsjonal-oppskrift':['finne_enhetsmengde','skalere_blandingsforhold'],
'omvendt-med-fastledd':['lage_prismodell','skille_felles_og_personlig_kostnad'],
'lineaer-fra-to-priser':['finne_stigningstall','finne_konstantledd'],
'budsjett-heltall':['lose_ulikhet','tolke_heltallsgrense'],
'rektangulaert-rutemonster':['generalisere','utvide_produkt'],
'tilvekst-og-startnummer':['telle_vekststeg','bruke_aritmetisk_tallfolge'],
'manglende-observasjon':['finne_sum_fra_gjennomsnitt','finne_ukjent_observasjon'],
'ekstremverdi-sentralmaal':['beregne_nytt_gjennomsnitt','tolke_median'],
'kumulativ-antall':['lese_frekvenstabell','tolke_kumulativ_frekvens'],
'klassemidtpunkt-anslag':['beregne_klassemidtpunkt','vekte_grupperte_data'],
'kode-betinget-sum':['spore_lokke','tolke_betingelse'],
'kode-tolkning-tillegg':['tolke_utskrift','skille_sluttverdi_og_sum'],
'samme-gjennomsnitt-spredning':['sammenlikne_spredning','begrunne'],
'energi-startverdi':['sette_inn_null','tolke_startverdi'],
'energi-modellverdi':['beregne_modellverdi','avrunde'],
'energi-gjennomsnittlig-vekstfart':['beregne_vekstfart','tolke_fortegn'],
'energi-modellbegrensning':['vurdere_nedre_grense','begrunne'],
'foerste-hele-periode':['lose_eksponentialulikhet','kontrollere_terskel'],
'finne-aarlig-vekst':['finne_vekstfaktor','tilbakeberegne_prosent'],
'tre-avtaler-intervall':['sammenlikne_tre_modeller','finne_heltallsintervall'],
'lineaer-regresjon-data':['lineaer_regresjon','tolke_koeffisienter'],
'eksponentialregresjon-data':['logaritmisk_regresjon','omregne_koeffisienter'],
'potensmodell-relativ-endring':['tolke_potensmodell','beregne_prosentendring'],
'vektet-gjennomsnitt-grupper':['vekte_gruppemidler','finne_samlet_gjennomsnitt'],
'populasjonsstandardavvik':['beregne_standardavvik','velge_populasjonsmaal'],
'histogram-hoeyder':['beregne_intervallbredde','finne_frekvenstetthet'],
'median-interpolasjon':['finne_medianintervall','interpolere'],
'konstruere-datasett':['konstruere_data','kontrollere_flere_vilkaar'],
'forbruk-per-person':['beregne_forholdstall','sammenlikne_prosentgrunnlag'],
'indeks-nytt-grunnlag':['tolke_indeks','bytte_sammenlikningsgrunnlag'],
'data-konklusjon':['vurdere_datagrunnlag','begrunne'],
'sparing-innskudd-foer-rente':['spore_sparemodell','tolke_innskuddstidspunkt'],
'kode-terskel-tolkning':['spore_while','kontrollere_stoppvilkaar']}
SKILLS={k.strip():v for k,v in SKILLS.items()}
for q in new:
 f=q['kontroll']['metode'];q['ferdighet']=SKILLS[f]
 if f=='andel-og-prosentpoeng':
  q['hint'][2]=q['hint'][2].replace('Bruk \\(', 'Bruk \\(d=').replace('forskjellen delt på','\\(d\\) delt på')
 if f=='fravaerende-andel' and q['fasit']['verdier'][0]['verdi']==100:q['sporsmal']+=' Hele gruppen regnes som 100 %.'
 if f=='potensmodell-relativ-endring':q['hint']=[h.replace('gang med 100','gang med hundre') for h in q['hint']]
 if f=='kode-terskel-tolkning':q['sporsmal']='Programmet undersøker salgsprisen i kroner på brukt utstyr. Prisen avtar én gang per år. Hvor mange år går det før prisen er på eller under grensen i testen? Lever årstallet som programmet skriver ut.'
 if q['fasit']['type']=='valg':
  explanations={
   'kode-tolkning-tillegg':{'Summen':'Ingen egen totalsum samler mellomverdiene. Variabelen antall erstattes av et nytt antall for hver runde.','Antall ganger':'Antall runder styres av range, mens print viser innholdet i variabelen antall.','Startantallet':'Startantallet endres inne i løkken før print-linjen kjøres.'},
   'samme-gjennomsnitt-spredning':{},
   'energi-modellbegrensning':{'Ja, samme':'Den prosentvise nedgangen gjelder bare potensleddet. Konstantleddet kommer i tillegg ved alle tillatte tidspunkt.','Ja, konstantleddet':'Konstantleddet står utenfor multiplikasjonen med vekstfaktoren og endres derfor ikke.'},
   'data-konklusjon':{'Utlån':'Når besøk øker raskere i prosent enn utlån, faller forholdet utlån per besøk.','Antall forskjellige':'Én person kan stå for flere besøk. Besøkstallene bestemmer derfor ikke antall ulike personer.','Lengre':'Tallene viser antall besøk og utlån. De inneholder ingen sammenlikning som fastslår hva som forårsaket endringen.'}}
  wrong={}
  for option in q['fasit']['alternativer']:
   if option in q['fasit']['riktige']:continue
   if f=='samme-gjennomsnitt-spredning':
    vals=list(map(int,option.split(', ')));wrong[option]=f'Disse tallene har variasjonsbredde {max(vals)-min(vals)}, fordi ytterverdiene er ulike. Lik gjennomsnittsverdi er ikke det samme som lik spredning.'
   else:wrong[option]=next(v for k,v in explanations[f].items() if option.startswith(k))
  q['laeringsstotte']['feilvalg']=wrong

for q in new:
 if q['fasit'].get('konstruksjon'):
  for field in q['kontroll']['svarfelt']:field['maks_poeng']=0
  q['kontroll']['samlet_maks_poeng']=2
 elif q['fasit']['type']=='valg':
  q['kontroll']['svarfelt']=[{'id':q['id']+'-valg','svarform':'enkeltvalg','maks_poeng':1,'riktig_alternativ':q['fasit']['riktige'][0]}]
bank=json.loads(PATH.read_text())
if len(bank['oppgaver'])!=515:raise SystemExit('Expected the unchanged 515-question baseline; refusing to rewrite the bank.')
assert not ({q['id'] for q in new}&{q['id'] for q in bank['oppgaver']})
bank['oppgaver']+=new;bank['oppgavegrupper']+=groups
bank['samling'].update(antall=915,versjon='2027.24')
bank['eksamensprofil']['del_1']='462 oppgaver uten hjelpemidler.'
bank['eksamensprofil']['del_2']='453 oppgaver med hjelpemidler: 213 selvstendige oppgaver og 240 deloppgaver i 60 sammenhengende kasus.'
bank['opphav']['merknad']='Originalskrevne eksamenslignende øvingsoppgaver med utgangspunkt i 2P-Y-profilen. Utvidet med 400 oppgaver 2026-09-07. Alle svar vurderes automatisk; begreper og hint åpnes på forespørsel og tilbakemelding gis etter innsending. Nivåene er faglige vurderinger, ikke elevutprøvde målinger eller opplysninger om neste eksamen.'
qs=bank['oppgaver'];stats=bank['statistikk'];stats['antall_oppgaver']=len(qs)
for name,key in [('del','del'),('niva','niva'),('tema','tema'),('hjelpemidler','hjelpemidler')]:stats['fordeling_'+name]=dict(sorted(Counter(str(q[key]) for q in qs).items()))
stats['fordeling_svarformat']=dict(Counter(q['fasit']['type'] for q in qs))
stats.update(antall_del2_oppgavegrupper=len(bank['oppgavegrupper']),antall_variantfamilier=len(set(q['variantfamilie'] for q in qs)),antall_med_visualisering=sum('visualisering' in q for q in qs),antall_programmeringsoppgaver=sum(q['tema']=='programmering' for q in qs),antall_aapne_svar=0,antall_flervalg_med_flere_riktige=sum(bool(q['fasit'].get('flervalg')) for q in qs))
PATH.write_text(json.dumps(bank,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'new':len(new),'groups':len(groups),'stats':stats},ensure_ascii=False))
