import fs from "node:fs";

const file = new URL("../public/oppgaver.json", import.meta.url);
const bank = JSON.parse(fs.readFileSync(file, "utf8"));
const h = String.raw;

const hints = {
  "g-01": [
    h`I dette regnestykket står det både pluss og gange. Regnerekkefølgen sier at vi skal regne gange før pluss.`,
    h`Se derfor først bare på $$4\cdot5$$. Dette betyr fire grupper med fem i hver.`,
    h`Fire femmere er $$5+5+5+5=20$$. Altså er $$4\cdot5=20$$.`,
    h`Bytt ut $$4\cdot5$$ med 20. Da blir hele regnestykket $$3+20$$.`,
    h`Regn ut til slutt: $$3+20=23$$. Svaret er 23.`,
  ],
  "g-02": [
    h`Brøkstreken betyr deling, men den virker også som en parentes. Derfor regner vi først ut alt som står over brøkstreken.`,
    h`Over brøkstreken står $$18-6$$. Trekk 6 fra 18: $$18-6=12$$.`,
    h`Nå kan vi erstatte telleren $$18-6$$ med 12. Brøken blir da $$\frac{12}{3}$$.`,
    h`Brøkstreken betyr deling, så $$\frac{12}{3}$$ betyr $$12:3$$.`,
    h`Tenk: Hvilket tall ganger 3 blir 12? Siden $$4\cdot3=12$$, er $$12:3=4$$.`,
    h`Svaret er 4.`,
  ],
  "g-03": [
    h`I brøken $$\frac{3}{4}$$ er 4 nevneren. Den forteller at 20 skal deles i fire like store deler.`,
    h`Finn først størrelsen på én del: $$20:4=5$$. Én firedel av 20 er altså 5.`,
    h`Tallet 3 øverst i brøken er telleren. Det forteller at vi skal ha tre slike deler.`,
    h`Tre deler på 5 hver blir $$5+5+5=15$$. Det samme kan skrives $$3\cdot5=15$$.`,
    h`Dermed er $$\frac{3}{4}$$ av 20 lik 15.`,
  ],
  "g-04": [
    h`I brøken $$\frac{2}{5}$$ forteller nevneren 5 at 30 skal deles i fem like store deler.`,
    h`Finn først én femdel: $$30:5=6$$. Hver del er altså 6.`,
    h`Telleren 2 forteller at vi skal ha to av disse delene.`,
    h`To deler på 6 hver blir $$6+6=12$$. Det samme kan skrives $$2\cdot6=12$$.`,
    h`Dermed er $$\frac{2}{5}$$ av 30 lik 12.`,
  ],
  "g-05": [
    h`Kilogram og gram er to enheter for masse. Sammenhengen er $$1\text{ kg}=1000\text{ g}$$.`,
    h`Det betyr at hvert kilogram inneholder 1000 gram. Derfor ganger vi antall kilogram med 1000 når vi går fra kg til g.`,
    h`Skriv regnestykket: $$1,4\cdot1000$$.`,
    h`Tallet 1,4 består av 1 kg og 0,4 kg. Det gir $$1\cdot1000=1000$$ gram og $$0,4\cdot1000=400$$ gram.`,
    h`Legg sammen delene: $$1000+400=1400$$.`,
    h`Dermed er $$1,4\text{ kg}=1400\text{ g}$$. Svaret er 1400 gram.`,
  ],
  "g-06": [
    h`Sammenhengen mellom gram og kilogram er $$1000\text{ g}=1\text{ kg}$$.`,
    h`Vi skal finne hvor mange grupper på 1000 gram det er i 2500 gram. Derfor deler vi på 1000.`,
    h`Skriv regnestykket: $$2500:1000$$.`,
    h`2000 gram er 2 kilogram, fordi $$2000:1000=2$$.`,
    h`De siste 500 grammene er et halvt kilogram, fordi $$500:1000=0,5$$.`,
    h`Legg sammen: $$2+0,5=2,5$$. Dermed er $$2500\text{ g}=2,5\text{ kg}$$.`,
  ],
  "g-07": [
    h`Å runde av til nærmeste tier betyr å velge det nærmeste tallet som slutter på 0.`,
    h`Tierne på hver side av 348 er 340 og 350.`,
    h`348 ligger 8 over 340, fordi $$348-340=8$$.`,
    h`348 ligger bare 2 under 350, fordi $$350-348=2$$.`,
    h`Siden avstanden 2 er mindre enn avstanden 8, ligger 348 nærmest 350.`,
    h`348 rundet av til nærmeste tier er derfor 350.`,
  ],
  "g-08": [
    h`Å runde av til nærmeste hundrer betyr å velge det nærmeste tallet som slutter på to nuller.`,
    h`Hundretallene på hver side av 872 er 800 og 900.`,
    h`872 ligger 72 over 800, fordi $$872-800=72$$.`,
    h`872 ligger 28 under 900, fordi $$900-872=28$$.`,
    h`Siden 28 er mindre enn 72, ligger 872 nærmest 900.`,
    h`872 rundet av til nærmeste hundrer er derfor 900.`,
  ],
  "g-09": [
    h`Programmet legger først sammen alle tallene og deler deretter på hvor mange tall det er. Dette er oppskriften på å finne gjennomsnittet.`,
    h`Legg sammen de to første tallene: $$2+4=6$$.`,
    h`Legg til 8: $$6+8=14$$.`,
    h`Legg til 16: $$14+16=30$$.`,
    h`Legg til det siste tallet 20: $$30+20=50$$. Summen er altså 50.`,
    h`Tell tallene: 2, 4, 8, 16 og 20. Det er 5 tall.`,
    h`Del summen på antallet: $$50:5=10$$, fordi $$5\cdot10=50$$.`,
    h`Programmet skriver ut 10.`,
  ],
  "g-10": [
    h`Programmet finner gjennomsnittet: først summen av tallene, og så summen delt på antall tall.`,
    h`Legg sammen de to første tallene: $$3+5=8$$.`,
    h`Legg til 7: $$8+7=15$$.`,
    h`Legg til 9: $$15+9=24$$. Summen er 24.`,
    h`Det er fire tall: 3, 5, 7 og 9.`,
    h`Del summen på antallet: $$24:4=6$$, fordi $$4\cdot6=24$$.`,
    h`Programmet skriver ut 6.`,
  ],
  "p-01": [
    h`Ordet prosent betyr «per hundre», altså «av 100». Symbolet for prosent er %.`,
    h`Brøken $$\frac{34}{100}$$ betyr 34 av 100.`,
    h`Når nevneren allerede er 100, er tallet i telleren prosenttallet.`,
    h`Telleren er 34. Derfor er $$\frac{34}{100}=34\%$$.`,
    h`Svaret er 34 %.`,
  ],
  "p-02": [
    h`Prosent betyr «av 100». Derfor vil vi skrive brøken slik at nevneren blir 100.`,
    h`Nevneren er nå 20. Spør: Hva må 20 ganges med for å bli 100?`,
    h`Siden $$20\cdot5=100$$, må nevneren ganges med 5.`,
    h`For at brøken skal beholde samme verdi, må vi gange både teller og nevner med det samme tallet.`,
    h`Gang telleren: $$7\cdot5=35$$. Gang nevneren: $$20\cdot5=100$$.`,
    h`Dermed er $$\frac{7}{20}=\frac{35}{100}$$.`,
    h`Brøken $$\frac{35}{100}$$ betyr 35 av 100, altså 35 %. Svaret er 35 %.`,
  ],
  "p-03": [
    h`3 % betyr 3 av 100. Vi kan først finne 1 % og deretter gange med 3.`,
    h`1 % er det samme som én hundredel. Derfor finner vi 1 % av 1200 ved å dele 1200 på 100.`,
    h`Regn ut $$1200:100$$. Å dele på 100 flytter kommaet to plasser mot venstre: $$1200\rightarrow12$$.`,
    h`Dermed er 1 % av 1200 kr lik 12 kr.`,
    h`3 % er tre ganger så mye som 1 %. Regnestykket blir $$3\cdot12$$.`,
    h`Tre tolvere er $$12+12+12=36$$. Altså er $$3\cdot12=36$$.`,
    h`3 % av 1200 kr er 36 kr.`,
  ],
  "p-04": [
    h`20 % betyr 20 av 100. Som brøk er dette $$\frac{20}{100}$$.`,
    h`Forkort brøken ved å dele både 20 og 100 på 20: $$\frac{20}{100}=\frac{1}{5}$$.`,
    h`Vi skal altså finne én femdel av 5200 egg.`,
    h`Én femdel finner vi ved å dele på 5: $$5200:5$$.`,
    h`Del opp 5200 i 5000 og 200. Da kan vi regne $$5000:5=1000$$ og $$200:5=40$$.`,
    h`Legg sammen svarene: $$1000+40=1040$$.`,
    h`20 % av 5200 egg er derfor 1040 egg.`,
  ],
  "p-05": [
    h`Spørsmålet er hvor stor del 80 er av 400. Her er 80 delen og 400 det hele.`,
    h`Skriv delen over det hele: $$\frac{80}{400}$$.`,
    h`For å gjøre brøken enklere kan vi dele både teller og nevner på 80.`,
    h`Regn ut: $$80:80=1$$ og $$400:80=5$$. Dermed er $$\frac{80}{400}=\frac{1}{5}$$.`,
    h`Prosent betyr «av 100», så vi ønsker 100 i nevneren. Siden $$5\cdot20=100$$, ganger vi både teller og nevner med 20.`,
    h`Da får vi $$\frac{1}{5}=\frac{1\cdot20}{5\cdot20}=\frac{20}{100}$$.`,
    h`$$\frac{20}{100}$$ betyr 20 av 100, altså 20 %. 80 kr er derfor 20 % av 400 kr.`,
  ],
  "p-06": [
    h`Vi skal finne hvor stor del 6 vogner er av totalt 20 vogner.`,
    h`Skriv delen over det hele: $$\frac{6}{20}$$.`,
    h`Prosent betyr «av 100». Derfor vil vi få 100 i nevneren.`,
    h`Siden $$20\cdot5=100$$, ganger vi både teller og nevner med 5.`,
    h`Regn ut telleren: $$6\cdot5=30$$. Nevneren blir $$20\cdot5=100$$.`,
    h`Dermed er $$\frac{6}{20}=\frac{30}{100}$$.`,
    h`30 av 100 er 30 %. Svaret er 30 %.`,
  ],
  "p-07": [
    h`Hele klassen er 100 %. Oppgaven forteller at 40 % av klassen er 12 elever.`,
    h`Vi går først fra 40 % til 10 %. Det er nyttig fordi det er lett å gå videre fra 10 % til 100 %.`,
    h`40 % består av fire grupper på 10 %, fordi $$40:10=4$$.`,
    h`Når 40 % er 12 elever, finner vi 10 % ved å dele elevtallet på 4: $$12:4=3$$.`,
    h`Dermed tilsvarer 10 % av klassen 3 elever.`,
    h`100 % består av ti grupper på 10 %, fordi $$100:10=10$$.`,
    h`Gang derfor 3 elever med 10: $$3\cdot10=30$$.`,
    h`100 % er hele klassen. Det er derfor 30 elever i klassen.`,
  ],
  "p-08": [
    h`Hele klassen er 100 %. Når 88 % deltar, er resten av prosentene elevene som ikke deltar.`,
    h`Finn resten: $$100\%-88\%=12\%$$. Altså deltar 12 % ikke.`,
    h`Oppgaven sier at 3 elever ikke deltar. Dermed tilsvarer 12 % akkurat 3 elever.`,
    h`Vi ønsker å finne hvor mange elever 4 % tilsvarer. 4 % er en tredel av 12 %, fordi $$12:3=4$$.`,
    h`Del også elevtallet på 3: $$3:3=1$$. Dermed tilsvarer 4 % én elev.`,
    h`Nå går vi fra 4 % til 100 %. Spør: Hvor mange grupper på 4 % er det i 100 %?`,
    h`Regn ut $$100:4=25$$. Det er altså 25 slike grupper.`,
    h`Hver gruppe på 4 % er én elev. Da er 25 grupper $$25\cdot1=25$$ elever.`,
    h`Det er 25 elever i klassen.`,
  ],
  "p-09": [
    h`Ved prosentvis økning sammenligner vi økningen med den gamle verdien. Den gamle prisen er 200 kr.`,
    h`Finn først hvor mange kroner prisen øker: $$250-200=50$$.`,
    h`Skriv økningen som en del av den gamle prisen: $$\frac{50}{200}$$.`,
    h`Prosent betyr «av 100». Derfor vil vi skrive brøken med 100 i nevneren.`,
    h`Del både teller og nevner på 2: $$50:2=25$$ og $$200:2=100$$.`,
    h`Dermed er $$\frac{50}{200}=\frac{25}{100}$$.`,
    h`Brøken $$\frac{25}{100}$$ betyr 25 av 100. Det er det samme som 25 %.`,
    h`Prisen øker derfor med 25 %.`,
  ],
  "p-10": [
    h`Ved prosentvis nedgang sammenligner vi avslaget med den gamle prisen. Den gamle prisen er 4800 kr.`,
    h`Avslaget er 1200 kr. Skriv avslaget som en del av den gamle prisen: $$\frac{1200}{4800}$$.`,
    h`Vi kan forkorte brøken ved å dele både teller og nevner på 1200.`,
    h`Regn ut: $$1200:1200=1$$ og $$4800:1200=4$$. Dermed er brøken $$\frac{1}{4}$$.`,
    h`Prosent betyr «av 100». For å få 100 i nevneren ganger vi 4 med 25, fordi $$4\cdot25=100$$.`,
    h`Gang også telleren med 25: $$1\cdot25=25$$. Da får vi $$\frac{1}{4}=\frac{25}{100}$$.`,
    h`25 av 100 er 25 %. Prisen er derfor satt ned med 25 %.`,
  ],
  "v-01": [
    h`En vekstfaktor forteller hvor stor den nye verdien er sammenlignet med den gamle. Vekstfaktor 1 betyr at 100 % er igjen og at ingenting har endret seg.`,
    h`Vekstfaktoren er 1,4. Finn hvor mye større den er enn 1: $$1,4-1=0,4$$.`,
    h`Tallet 0,4 er selve økningen skrevet som desimaltall.`,
    h`For å gjøre et desimaltall om til prosent ganger vi med 100. Regnestykket er $$0,4\cdot100=40$$.`,
    h`Dette virker fordi $$0,4=\frac{40}{100}$$, og $$\frac{40}{100}=40\%$$.`,
    h`Den prosentvise økningen er derfor 40 %.`,
  ],
  "v-02": [
    h`Vekstfaktor 1 betyr at 100 % av den gamle verdien er igjen.`,
    h`Vekstfaktor 0,67 betyr at den nye verdien er 0,67 av den gamle.`,
    h`Gjør 0,67 om til prosent: $$0,67\cdot100=67$$. Det betyr at 67 % er igjen.`,
    h`Nedgangen er det som mangler opp til 100 %. Regn ut $$100\%-67\%=33\%$$.`,
    h`Vi kan kontrollere med desimaltall: $$1-0,67=0,33$$, og $$0,33=33\%$$.`,
    h`Den prosentvise nedgangen er 33 %.`,
  ],
  "v-03": [
    h`En vekstfaktor forteller hvor mye vi skal gange den gamle verdien med. Uten endring er vekstfaktoren 1.`,
    h`Ved 8 % økning skal hele den gamle verdien, altså 100 %, fortsatt være med. I tillegg kommer 8 %.`,
    h`Den nye verdien er derfor $$100\%+8\%=108\%$$ av den gamle.`,
    h`For å gjøre prosent om til desimaltall deler vi på 100: $$108\%=\frac{108}{100}=1,08$$.`,
    h`Vi skal altså gange med 1,08. Vekstfaktoren er 1,08.`,
  ],
  "v-04": [
    h`Uten endring er 100 % av den gamle verdien igjen, og vekstfaktoren er 1.`,
    h`Ved 35 % nedgang forsvinner 35 % fra de opprinnelige 100 %.`,
    h`Finn hvor mange prosent som er igjen: $$100\%-35\%=65\%$$.`,
    h`Gjør 65 % om til desimaltall ved å dele på 100: $$65\%=\frac{65}{100}=0,65$$.`,
    h`Vi skal altså gange med 0,65. Vekstfaktoren er 0,65.`,
  ],
  "v-05": [
    h`Prisen øker med 20 %. Det betyr at den nye prisen består av den gamle prisen på 100 % pluss 20 %.`,
    h`Den nye prisen er derfor $$100\%+20\%=120\%$$ av den gamle prisen.`,
    h`120 % skrevet som desimaltall er $$\frac{120}{100}=1,20$$. Vekstfaktoren er altså 1,2.`,
    h`Ny pris finner vi ved å gange gammel pris med vekstfaktoren: $$500\cdot1,2$$.`,
    h`Tallet 1,2 kan deles i 1 og 0,2. Derfor er $$500\cdot1,2=500\cdot1+500\cdot0,2$$.`,
    h`$$500\cdot1=500$$. Dessuten er 0,2 det samme som en femdel, så $$500\cdot0,2=500:5=100$$.`,
    h`Legg sammen: $$500+100=600$$.`,
    h`Den nye prisen er 600 kr.`,
  ],
  "v-06": [
    h`Et avslag på 20 % betyr at 20 % forsvinner fra de opprinnelige 100 %.`,
    h`Finn hvor mye som er igjen: $$100\%-20\%=80\%$$.`,
    h`80 % skrevet som desimaltall er $$\frac{80}{100}=0,8$$. Derfor er vekstfaktoren 0,8.`,
    h`Den nye prisen er den gamle prisen ganget med 0,8. Vi kan skrive $$\text{gammel pris}\cdot0,8=400$$.`,
    h`For å finne den gamle prisen gjør vi motsatt regneoperasjon: Vi deler 400 på 0,8.`,
    h`Regnestykket er $$400:0,8$$. Gjør det enklere ved å gange begge tall med 10: $$400:0,8=4000:8$$.`,
    h`Regn ut $$4000:8=500$$, fordi $$8\cdot500=4000$$.`,
    h`Kontroll: 20 % av 500 er 100, og $$500-100=400$$. Varen kostet 500 kr før avslaget.`,
  ],
  "v-07": [
    h`Vi må regne endringene i riktig rekkefølge. Startprisen er 100 kr.`,
    h`Først settes prisen ned med 20 %. Da er $$100\%-20\%=80\%$$ igjen.`,
    h`80 % av 100 kr er 80 kr. Etter avslaget koster varen altså 80 kr.`,
    h`Deretter øker den nye prisen på 80 kr med 20 %. De 20 prosentene skal nå regnes av 80, ikke av 100.`,
    h`10 % av 80 er $$80:10=8$$. Derfor er 20 % to slike deler: $$2\cdot8=16$$.`,
    h`Økningen er 16 kr. Legg den til prisen 80 kr: $$80+16=96$$.`,
    h`Varen koster til slutt 96 kr.`,
  ],
  "v-08": [
    h`Når ingen startverdi er oppgitt, kan vi velge 100. Da blir prosentregningen enkel.`,
    h`En økning på 10 % av 100 er 10, fordi $$100:10=10$$.`,
    h`Etter økningen er verdien $$100+10=110$$.`,
    h`Nå skal verdien synke med 10 %. Denne gangen regnes 10 % av den nye verdien 110.`,
    h`10 % av 110 er $$110:10=11$$.`,
    h`Trekk nedgangen fra 110: $$110-11=99$$.`,
    h`Verdien startet på 100 og endte på 99. Den har derfor gått ned med $$100-99=1$$.`,
    h`Når startverdien er 100, er en nedgang på 1 det samme som 1 av 100, altså 1 %.`,
    h`Den samlede prosentvise nedgangen er 1 %.`,
  ],
  "v-09": [
    h`Prosentpoeng er forskjellen mellom to prosenttall. Vi skal bare trekke det nye prosenttallet fra det gamle.`,
    h`Renten går fra 6 % til 5,4 %, så regnestykket er $$6-5,4$$.`,
    h`Skriv gjerne 6 som 6,0 slik at desimalkommaene står under hverandre: $$6,0-5,4$$.`,
    h`Fra 5,4 til 6,0 er det 0,6. Derfor er $$6,0-5,4=0,6$$.`,
    h`Renten synker med 0,6 prosentpoeng.`,
  ],
  "v-10": [
    h`Prosentpoeng er den direkte forskjellen mellom to prosenttall.`,
    h`Oppslutningen går fra 16 % til 20 %. Siden den øker, trekker vi den gamle verdien fra den nye.`,
    h`Skriv regnestykket: $$20-16$$.`,
    h`Regn ut: $$20-16=4$$.`,
    h`Økningen er 4 prosentpoeng.`,
  ],
  "s-01": [
    h`Gjennomsnitt er summen av alle tallene delt på hvor mange tall det er.`,
    h`Legg sammen litt etter litt: $$2+4=6$$.`,
    h`Fortsett med 8: $$6+8=14$$.`,
    h`Legg til 16: $$14+16=30$$.`,
    h`Legg til 20: $$30+20=50$$. Summen er 50.`,
    h`Tell tallene: Det er 5 tall.`,
    h`Del summen på antallet: $$50:5=10$$, fordi $$5\cdot10=50$$.`,
    h`Gjennomsnittet er 10.`,
  ],
  "s-02": [
    h`Gjennomsnitt finner vi ved å legge sammen alle tallene og dele summen på antall tall.`,
    h`Legg sammen litt etter litt: $$6+3=9$$.`,
    h`Legg til 5: $$9+5=14$$.`,
    h`Legg til 4: $$14+4=18$$.`,
    h`Legg til 7: $$18+7=25$$. Summen er 25.`,
    h`Det er 5 tall i listen.`,
    h`Del summen på antallet: $$25:5=5$$.`,
    h`Gjennomsnittet er 5.`,
  ],
  "s-03": [
    h`Medianen er tallet i midten når tallene står i stigende rekkefølge, altså fra minst til størst.`,
    h`Tallene står allerede i stigende rekkefølge: 4, 8, 9, 11, 12, 20.`,
    h`Det er 6 tall. Når antallet er partall, finnes det ikke ett enkelt tall i midten; det finnes to.`,
    h`Tell inn fra begge sider. De to midterste tallene er 9 og 11.`,
    h`Medianen er gjennomsnittet av disse to tallene. Legg dem sammen: $$9+11=20$$.`,
    h`Del summen på 2: $$20:2=10$$.`,
    h`Medianen er 10.`,
  ],
  "s-04": [
    h`Medianen er tallet i midten når tallene står fra minst til størst.`,
    h`Tallene står ikke i riktig rekkefølge ennå. Sorter dem: $$2,\ 3,\ 5,\ 7,\ 9$$.`,
    h`Det er 5 tall. Med et oddetall antall verdier finnes det ett tall akkurat i midten.`,
    h`Det står to tall på hver side av 5: 2 og 3 til venstre, 7 og 9 til høyre.`,
    h`Dermed er 5 det midterste tallet. Medianen er 5.`,
  ],
  "s-05": [
    h`Typetallet er tallet som forekommer flest ganger i datasettet.`,
    h`Tallet 2 forekommer én gang. Tallet 3 forekommer to ganger.`,
    h`Tallet 4 forekommer én gang. Tallet 5 forekommer tre ganger.`,
    h`Tallet 6 forekommer én gang.`,
    h`Tre forekomster er flest. Derfor er 5 typetallet.`,
  ],
  "s-06": [
    h`Variasjonsbredden forteller hvor langt det er fra den minste til den største verdien.`,
    h`Finn først den minste verdien i listen. Den er 9.`,
    h`Finn deretter den største verdien. Den er 21.`,
    h`Variasjonsbredden er største verdi minus minste verdi: $$21-9$$.`,
    h`Regn ut $$21-9=12$$.`,
    h`Variasjonsbredden er 12.`,
  ],
  "s-07": [
    h`Relativ frekvens betyr hvor stor del en bestemt verdi utgjør av alle observasjonene.`,
    h`Tallet 6 forekommer 3 ganger, og det er 10 observasjoner totalt. Skriv derfor $$\frac{3}{10}$$.`,
    h`Prosent betyr «av 100». Vi vil derfor få 100 i nevneren.`,
    h`Siden $$10\cdot10=100$$, ganger vi både teller og nevner med 10.`,
    h`Telleren blir $$3\cdot10=30$$, og nevneren blir 100. Dermed er $$\frac{3}{10}=\frac{30}{100}$$.`,
    h`30 av 100 er 30 %. Den relative frekvensen er 30 %.`,
  ],
  "s-08": [
    h`Relativ frekvens sammenligner antallet som sykler med antallet elever totalt.`,
    h`8 elever sykler, og det er 40 elever. Skriv delen over det hele: $$\frac{8}{40}$$.`,
    h`Forkort ved å dele både teller og nevner på 8: $$8:8=1$$ og $$40:8=5$$.`,
    h`Da får vi $$\frac{8}{40}=\frac{1}{5}$$.`,
    h`Prosent betyr «av 100». Siden $$5\cdot20=100$$, ganger vi teller og nevner med 20.`,
    h`Da blir $$\frac{1}{5}=\frac{20}{100}$$.`,
    h`20 av 100 er 20 %. Den relative frekvensen er 20 %.`,
  ],
  "s-09": [
    h`Klassemidtpunktet er tallet som ligger nøyaktig midt mellom den nedre og den øvre grensen.`,
    h`Den nedre grensen er 20, og den øvre grensen er 40.`,
    h`Legg sammen grensene: $$20+40=60$$.`,
    h`For å finne tallet midt mellom dem deler vi summen på 2: $$60:2=30$$.`,
    h`Kontroll: Det er 10 fra 20 til 30 og 10 fra 30 til 40.`,
    h`Klassemidtpunktet er 30.`,
  ],
  "s-10": [
    h`Kumulativ frekvens betyr antallet som er samlet opp til og med en bestemt klasse.`,
    h`Etter den tredje klassen skal frekvensen fra klasse 1, klasse 2 og klasse 3 være med.`,
    h`Frekvensene er 4, 6 og 10. Legg først sammen de to første: $$4+6=10$$.`,
    h`Legg så til frekvensen i den tredje klassen: $$10+10=20$$.`,
    h`Den kumulative frekvensen etter den tredje klassen er 20.`,
  ],
  "po-01": [
    h`I potensen $$2^5$$ er 2 grunntallet og 5 eksponenten.`,
    h`Eksponenten 5 forteller at grunntallet 2 skal brukes som faktor fem ganger.`,
    h`Skriv derfor $$2^5=2\cdot2\cdot2\cdot2\cdot2$$.`,
    h`Gang de to første: $$2\cdot2=4$$.`,
    h`Gang videre med 2: $$4\cdot2=8$$.`,
    h`Gang videre: $$8\cdot2=16$$.`,
    h`Gang med den siste 2-eren: $$16\cdot2=32$$.`,
    h`Dermed er $$2^5=32$$.`,
  ],
  "po-02": [
    h`En negativ eksponent betyr at vi får den omvendte brøken av den samme potensen med positiv eksponent.`,
    h`Derfor er $$10^{-2}=\frac{1}{10^2}$$.`,
    h`Eksponenten 2 betyr at 10 skal ganges med seg selv to ganger: $$10^2=10\cdot10$$.`,
    h`Regn ut: $$10\cdot10=100$$. Da blir uttrykket $$\frac{1}{100}$$.`,
    h`Brøken $$\frac{1}{100}$$ betyr én hundredel.`,
    h`Én hundredel skrevet som desimaltall er 0,01, fordi 1 står på hundredelsplassen.`,
    h`Dermed er $$10^{-2}=0,01$$.`,
  ],
  "po-03": [
    h`Kvadratroten av 64 er det positive tallet som blir 64 når det ganges med seg selv.`,
    h`Vi leter altså etter et tall som passer i $$\square\cdot\square=64$$.`,
    h`Prøv 8: $$8\cdot8=64$$.`,
    h`Siden 8 ganget med seg selv blir 64, er $$\sqrt{64}=8$$.`,
  ],
  "po-04": [
    h`Kvadratroten av 10 000 er det positive tallet som blir 10 000 når det ganges med seg selv.`,
    h`Tenk på 100: Det kan skrives som $$10\cdot10$$.`,
    h`Da er $$100\cdot100=(10\cdot10)(10\cdot10)$$.`,
    h`Fire tiere ganget sammen gir 10 000: $$10\cdot10\cdot10\cdot10=10\,000$$.`,
    h`Dermed er $$100\cdot100=10\,000$$, og derfor er $$\sqrt{10\,000}=100$$.`,
  ],
  "po-05": [
    h`Uttrykket $$3\cdot10^5$$ betyr 3 ganget med en tierpotens.`,
    h`Eksponenten 5 betyr at 10 skal ganges med seg selv fem ganger.`,
    h`Skriv ut potensen: $$10^5=10\cdot10\cdot10\cdot10\cdot10=100\,000$$.`,
    h`Sett dette inn i uttrykket: $$3\cdot10^5=3\cdot100\,000$$.`,
    h`Tre grupper på 100 000 blir $$100\,000+100\,000+100\,000=300\,000$$.`,
    h`Som vanlig tall er svaret 300 000.`,
  ],
  "po-06": [
    h`Tallet er skrevet på standardform. Faktoren $$10^{-3}$$ betyr at 4,2 skal deles på 1000.`,
    h`Å dele på 1000 gjør tallet tusen ganger mindre. Det tilsvarer å flytte desimalkommaet tre plasser mot venstre.`,
    h`Start med 4,2. Første flytt gir $$4,2\rightarrow0,42$$.`,
    h`Andre flytt gir $$0,42\rightarrow0,042$$.`,
    h`Tredje flytt gir $$0,042\rightarrow0,0042$$.`,
    h`Dermed er $$4,2\cdot10^{-3}=0,0042$$.`,
  ],
  "po-07": [
    h`På standardform skriver vi et tall som $$a\cdot10^n$$, der tallet a er minst 1 og mindre enn 10.`,
    h`I 900 000 flytter vi kommaet til vi får et tall mellom 1 og 10. Da får vi 9.`,
    h`Tenk at kommaet står bakerst: $$900\,000,0$$.`,
    h`For å komme fra 900 000 til 9 flytter vi kommaet fem plasser mot venstre.`,
    h`Fem plasser gir tierpotensen $$10^5$$.`,
    h`Kontroll: $$10^5=100\,000$$ og $$9\cdot100\,000=900\,000$$.`,
    h`Standardformen er $$9\cdot10^5$$.`,
  ],
  "po-08": [
    h`På standardform skriver vi tallet som $$a\cdot10^n$$, der a er minst 1 og mindre enn 10.`,
    h`Flytt kommaet i 0,00025 mot høyre til du får et tall mellom 1 og 10.`,
    h`Tell flyttene: $$0,00025\rightarrow0,0025\rightarrow0,025\rightarrow0,25\rightarrow2,5$$. Det er fire plasser.`,
    h`Det opprinnelige tallet er mindre enn 1. Derfor skal eksponenten være negativ.`,
    h`Fire flytt mot høyre gir eksponenten −4.`,
    h`Kontroll: $$10^{-4}=0,0001$$, og $$2,5\cdot0,0001=0,00025$$.`,
    h`Standardformen er $$2,5\cdot10^{-4}$$.`,
  ],
  "po-09": [
    h`Vi kan gjøre multiplikasjonen enklere ved å skrive begge tall på standardform.`,
    h`Tallet 3 000 000 er $$3\cdot10^6$$, fordi $$10^6=1\,000\,000$$.`,
    h`Tallet 0,000 025 er $$2,5\cdot10^{-5}$$. Kommaet må flyttes fem plasser mot høyre for å få 2,5.`,
    h`Sett inn standardformene: $$(3\cdot10^6)(2,5\cdot10^{-5})$$.`,
    h`Gang først tallene foran tierpotensene: $$3\cdot2,5=7,5$$.`,
    h`Når vi ganger tierpotenser, legger vi sammen eksponentene: $$6+(-5)=1$$.`,
    h`Tierpotensdelen blir derfor $$10^1=10$$.`,
    h`Hele uttrykket er nå $$7,5\cdot10$$.`,
    h`Å gange med 10 flytter kommaet én plass mot høyre: $$7,5\rightarrow75$$. Svaret er 75.`,
  ],
  "po-10": [
    h`I brøken deler vi både tallene foran tierpotensene og selve tierpotensene.`,
    h`Del tallene foran: $$6:2=3$$.`,
    h`Når vi deler potenser med samme grunntall, trekker vi eksponenten i nevneren fra eksponenten i telleren.`,
    h`Her blir eksponenten $$5-2=3$$.`,
    h`Dermed er $$\frac{10^5}{10^2}=10^3$$.`,
    h`Sett delene sammen: $$\frac{6\cdot10^5}{2\cdot10^2}=3\cdot10^3$$.`,
    h`$$10^3=10\cdot10\cdot10=1000$$.`,
    h`Regn ut $$3\cdot1000=3000$$. Svaret er 3000.`,
  ],
  "pr-01": [
    h`Når pris og vekt er proporsjonale, koster hvert kilogram like mye. Derfor finner vi totalprisen ved å gange kiloprisen med antall kilogram.`,
    h`Kiloprisen er 120 kr, og vekten er 1,4 kg. Regnestykket blir $$120\cdot1,4$$.`,
    h`Tallet 1,4 betyr 1 hel og 0,4 ekstra. Derfor kan vi dele regningen i $$120\cdot1+120\cdot0,4$$.`,
    h`Den hele kiloen koster $$120\cdot1=120$$ kr.`,
    h`Desimaltallet 0,4 er det samme som brøken $$\frac{4}{10}$$. Det er fire tideler.`,
    h`Fire tideler er også 40 hundredeler: $$\frac{4}{10}=\frac{40}{100}=40\%$$. Derfor er $$0,4=40\%$$.`,
    h`Finn først 10 % av 120 kr ved å dele på 10: $$120:10=12$$ kr.`,
    h`40 % er fire ganger 10 %. Derfor er 40 % av 120 kr $$4\cdot12=48$$ kr.`,
    h`Legg sammen prisen for 1 kg og 0,4 kg: $$120+48=168$$.`,
    h`1,4 kg kyllingfilet koster 168 kr.`,
  ],
  "pr-02": [
    h`Kiloprisen er prisen for 1 kg. Først gjør vi kilogram om til gram: $$1\text{ kg}=1000\text{ g}$$.`,
    h`Vi skal finne hvilken del 250 g er av 1000 g.`,
    h`Fire grupper på 250 g blir 1000 g, fordi $$250+250+250+250=1000$$.`,
    h`Dermed er 250 g en firedel av 1 kg.`,
    h`Når vekten er en firedel av 1 kg, er prisen også en firedel av kiloprisen.`,
    h`Finn en firedel av 120 kr ved å dele på 4: $$120:4=30$$, fordi $$4\cdot30=120$$.`,
    h`250 g koster 30 kr.`,
  ],
  "pr-03": [
    h`To størrelser er proporsjonale når den ene alltid er et fast tall ganger den andre.`,
    h`Her koster hver billett 120 kr, og det finnes ingen startpris eller andre gebyrer.`,
    h`Totalprisen kan derfor skrives $$\text{totalpris}=120\cdot\text{antall billetter}$$.`,
    h`Kontroller med noen verdier: 1 billett koster 120 kr, og 2 billetter koster $$2\cdot120=240$$ kr.`,
    h`Når antall billetter dobles fra 1 til 2, dobles også prisen fra 120 til 240 kr.`,
    h`Det faste forholdstallet er 120 kr per billett. Størrelsene er derfor proporsjonale.`,
    h`Svaret er ja.`,
  ],
  "pr-04": [
    h`Ved proporsjonalitet må totalprisen være et fast tall ganger antall kilometer. Da må prisen også være 0 kr når antall kilometer er 0.`,
    h`Drosjen har en startpris på 80 kr. Den må betales selv om turen er 0 km.`,
    h`Prisregelen er $$\text{totalpris}=80+20\cdot\text{antall kilometer}$$.`,
    h`Ved 0 km er prisen $$80+20\cdot0=80$$ kr, ikke 0 kr.`,
    h`Startprisen gjør at prisen ikke er et fast tall ganger antall kilometer.`,
    h`Størrelsene er derfor ikke proporsjonale. Svaret er nei.`,
  ],
  "pr-05": [
    h`Ved omvendt proporsjonalitet blir den ene størrelsen mindre når den andre blir større, slik at produktet av dem er konstant.`,
    h`Den totale leieprisen er alltid 15 000 kr. Den endres ikke når antall elever endres.`,
    h`Pris per elev er derfor $$\frac{15\,000}{\text{antall elever}}$$.`,
    h`Hvis 10 elever deltar, blir prisen per elev $$15\,000:10=1500$$ kr.`,
    h`Hvis antallet dobles til 20 elever, blir prisen $$15\,000:20=750$$ kr. Prisen per elev er da halvert.`,
    h`Produktet er i begge tilfeller 15 000: $$10\cdot1500=15\,000$$ og $$20\cdot750=15\,000$$.`,
    h`Størrelsene er derfor omvendt proporsjonale. Svaret er ja.`,
  ],
  "pr-06": [
    h`Ved omvendt proporsjonalitet skal en dobling av antall elever halvere hele prisen per elev.`,
    h`Leiedelen per elev blir mindre når flere deltar, fordi den faste leiesummen deles på flere.`,
    h`Men hver elev betaler alltid 250 kr for mat. Denne delen blir ikke mindre når flere deltar.`,
    h`Samlet pris per elev er $$\frac{\text{fast leiesum}}{\text{antall elever}}+250$$.`,
    h`Når elevtallet dobles, halveres bare brøkdelen. Tillegget på 250 kr halveres ikke.`,
    h`Dermed blir ikke hele prisen per elev halvert.`,
    h`Størrelsene er derfor ikke omvendt proporsjonale. Svaret er nei.`,
  ],
  "pr-07": [
    h`Ti elever skal dele den faste summen 15 000 kr likt. Da bruker vi deling.`,
    h`Skriv regnestykket: $$15\,000:10$$.`,
    h`Å dele på 10 betyr å gjøre tallet ti ganger mindre. Da flyttes kommaet én plass mot venstre.`,
    h`Tenk at tallet er $$15\,000,0$$. Én plass mot venstre gir $$1500,0$$.`,
    h`Dermed er $$15\,000:10=1500$$.`,
    h`Hver elev betaler 1500 kr i leie.`,
  ],
  "pr-08": [
    h`Samlet pris per elev består av to deler: elevens del av leien og 250 kr til mat.`,
    h`Finn først leien per elev. Ti elever deler 15 000 kr, så regnestykket er $$15\,000:10$$.`,
    h`Å dele på 10 gir $$15\,000:10=1500$$. Leien er altså 1500 kr per elev.`,
    h`Legg til matprisen på 250 kr: $$1500+250$$.`,
    h`Legg først til 200: $$1500+200=1700$$. Legg så til 50: $$1700+50=1750$$.`,
    h`Samlet pris per elev er 1750 kr.`,
  ],
  "pr-09": [
    h`Ved proporsjonalitet kan sammenhengen skrives $$y=kx$$. Bokstaven k er tallet vi ganger x med for å få y.`,
    h`Vi vet at $$x=4$$ og $$y=28$$. Sett disse tallene inn: $$28=k\cdot4$$.`,
    h`Dette betyr at 4 ganger k er 28. For å finne k deler vi 28 på 4.`,
    h`Skriv $$k=28:4$$.`,
    h`Siden $$4\cdot7=28$$, er $$28:4=7$$.`,
    h`Kontroll: $$y=kx=7\cdot4=28$$. Det stemmer med oppgaven.`,
    h`Proporsjonalitetskonstanten er 7.`,
  ],
  "pr-10": [
    h`Ved proporsjonalitet bruker vi formelen $$y=kx$$.`,
    h`Her er proporsjonalitetskonstanten $$k=6$$, og $$x=5$$.`,
    h`Sett inn verdiene i formelen: $$y=6\cdot5$$.`,
    h`Fem seksere er $$6+6+6+6+6=30$$. Derfor er $$6\cdot5=30$$.`,
    h`Dermed er $$y=30$$.`,
  ],
  "f-01": [
    h`Uttrykket $$f(4)$$ betyr at vi skal bruke tallet 4 i stedet for x i funksjonen.`,
    h`Funksjonen er $$f(x)=3x+5$$. Bytt ut x med 4: $$f(4)=3\cdot4+5$$.`,
    h`Regnerekkefølgen sier at vi skal regne gange før pluss.`,
    h`Regn ut gangen: $$3\cdot4=12$$.`,
    h`Da står det igjen $$12+5$$.`,
    h`Regn ut: $$12+5=17$$.`,
    h`Dermed er $$f(4)=17$$.`,
  ],
  "f-02": [
    h`Uttrykket $$g(10)$$ betyr at x skal erstattes med 10 i funksjonen.`,
    h`Funksjonen er $$g(x)=\frac{200}{x}$$. Sett inn 10: $$g(10)=\frac{200}{10}$$.`,
    h`Brøkstreken betyr deling. Derfor skal vi regne $$200:10$$.`,
    h`Å dele på 10 flytter kommaet én plass mot venstre: $$200\rightarrow20$$.`,
    h`Dermed er $$200:10=20$$, og $$g(10)=20$$.`,
  ],
  "f-03": [
    h`En lineær funksjon kan skrives $$f(x)=ax+b$$. Tallet a forteller hvor mye f(x) endrer seg når x øker med 1.`,
    h`Se på endringen fra $$f(0)=5$$ til $$f(1)=8$$: $$8-5=3$$.`,
    h`Kontroller neste steg: Fra $$f(1)=8$$ til $$f(2)=11$$ er endringen $$11-8=3$$.`,
    h`Funksjonsverdien øker altså med 3 hver gang x øker med 1. Derfor er $$a=3$$.`,
    h`Funksjonen har nå formen $$f(x)=3x+b$$.`,
    h`Tallet b er funksjonsverdien når $$x=0$$, fordi $$3\cdot0=0$$.`,
    h`Oppgaven sier at $$f(0)=5$$. Derfor er $$b=5$$.`,
    h`Sett inn både a og b: $$f(x)=3x+5$$.`,
    h`Kontroll med $$x=2$$: $$3\cdot2+5=6+5=11$$. Det stemmer. Svaret er $$f(x)=3x+5$$.`,
  ],
  "f-04": [
    h`Totalprisen består av en fast del og en del som avhenger av hvor mange kilometer taxien kjører.`,
    h`Startprisen 80 kr er den faste delen. Den betales også når $$x=0$$.`,
    h`Taxien koster 20 kr for hver kilometer. Etter x kilometer blir kilometerdelen $$20\cdot x=20x$$.`,
    h`Legg sammen startprisen og kilometerdelen: $$P(x)=80+20x$$.`,
    h`Kontroll: Ved 1 km gir uttrykket $$80+20\cdot1=100$$ kr, altså 80 kr i startpris og 20 kr for én kilometer.`,
    h`Funksjonsuttrykket er $$P(x)=80+20x$$.`,
  ],
  "f-05": [
    h`Prisen per person finner vi ved å dele totalprisen på antall personer.`,
    h`Totalprisen er 8000 kr. Antall personer er skrevet med bokstaven x.`,
    h`Regnestykket blir derfor $$8000:x$$.`,
    h`Deling kan skrives som en brøk: $$8000:x=\frac{8000}{x}$$.`,
    h`Siden funksjonen heter f, skriver vi $$f(x)=\frac{8000}{x}$$.`,
    h`Uttrykket er altså $$f(x)=\frac{8000}{x}$$.`,
  ],
  "f-06": [
    h`I funksjonen står x for antall personer. Når 20 personer deltar, setter vi derfor $$x=20$$.`,
    h`Bytt ut x med 20: $$f(20)=\frac{8000}{20}$$.`,
    h`Brøkstreken betyr deling, så vi skal regne $$8000:20$$.`,
    h`Både 8000 og 20 kan deles på 10. Da blir regnestykket $$800:2$$.`,
    h`Halvparten av 800 er 400, så $$800:2=400$$.`,
    h`Kontroll: $$20\cdot400=8000$$. Prisen blir 400 kr per person.`,
  ],
  "f-07": [
    h`Oppgaven sier at funksjonsverdien skal være 14. Sett derfor funksjonsuttrykket lik 14: $$2x+4=14$$.`,
    h`Målet er å få x alene. På venstre side er 4 lagt til. Vi gjør det motsatte og trekker fra 4.`,
    h`Vi må gjøre det samme på begge sider for at likheten fortsatt skal stemme: $$2x+4-4=14-4$$.`,
    h`På venstre side forsvinner $$+4-4$$. På høyre side er $$14-4=10$$. Da får vi $$2x=10$$.`,
    h`Uttrykket $$2x$$ betyr $$2\cdot x$$. For å få x alene deler vi begge sider på 2.`,
    h`Da blir $$x=10:2$$.`,
    h`Siden $$10:2=5$$, er $$x=5$$.`,
    h`Kontroll: $$f(5)=2\cdot5+4=10+4=14$$. Svaret er 5.`,
  ],
  "f-08": [
    h`Oppgaven sier at $$g(x)=17$$. Sett derfor funksjonsuttrykket lik 17: $$5x-3=17$$.`,
    h`Målet er å få x alene. På venstre side er 3 trukket fra. Vi gjør det motsatte og legger til 3.`,
    h`Legg til 3 på begge sider: $$5x-3+3=17+3$$.`,
    h`På venstre side forsvinner $$-3+3$$. På høyre side er $$17+3=20$$. Da får vi $$5x=20$$.`,
    h`Uttrykket $$5x$$ betyr $$5\cdot x$$. Del begge sider på 5 for å få x alene.`,
    h`Da blir $$x=20:5$$.`,
    h`Siden $$20:5=4$$, er $$x=4$$.`,
    h`Kontroll: $$g(4)=5\cdot4-3=20-3=17$$. Svaret er 4.`,
  ],
  "f-09": [
    h`I uttrykket $$K(x)=500+80x$$ står tallet 500 alene. Det er ikke ganget med x.`,
    h`For å se hva 500 betyr, kan vi undersøke kostnaden når $$x=0$$.`,
    h`Sett inn 0: $$K(0)=500+80\cdot0$$.`,
    h`Siden $$80\cdot0=0$$, blir $$K(0)=500+0=500$$.`,
    h`Kostnaden er altså 500 kr selv når x er 0.`,
    h`Tallet 500 er derfor den faste kostnaden.`,
  ],
  "f-10": [
    h`I uttrykket $$K(x)=500+80x$$ står tallet 80 foran x. Det betyr at 80 ganges med verdien av x.`,
    h`Se på $$x=1$$: Den variable delen er $$80\cdot1=80$$ kr.`,
    h`Se på $$x=2$$: Den variable delen er $$80\cdot2=160$$ kr.`,
    h`Når x øker fra 1 til 2, øker denne delen med $$160-80=80$$ kr.`,
    h`Det samme skjer hver gang x øker med 1. Tallet 80 er derfor kostnaden per ekstra enhet.`,
    h`80 betyr 80 kr per enhet.`,
  ],
  "m-01": [
    h`For å fortsette mønsteret må vi finne hvor mye antallet øker fra én figur til den neste.`,
    h`Fra figur 1 til figur 2 går antallet fra 4 til 7. Forskjellen er $$7-4=3$$.`,
    h`Kontroller neste steg: $$10-7=3$$.`,
    h`Kontroller også det siste steget: $$13-10=3$$.`,
    h`Antallet øker altså med 3 for hver ny figur.`,
    h`Figur 4 har 13 prikker. Legg til 3 for å få figur 5: $$13+3=16$$.`,
    h`Figur 5 har 16 prikker.`,
  ],
  "m-02": [
    h`Finn først hvor mye antallet ruter øker fra én figur til den neste.`,
    h`Fra 5 til 9 er økningen $$9-5=4$$.`,
    h`Fra 9 til 13 er økningen $$13-9=4$$.`,
    h`Fra 13 til 17 er økningen $$17-13=4$$.`,
    h`Mønsteret øker altså med 4 ruter for hver ny figur.`,
    h`Figur 4 har 17 ruter. Legg til 4: $$17+4=21$$.`,
    h`Figur 5 har 21 ruter.`,
  ],
  "m-03": [
    h`Bokstaven n står for figurnummeret. Vi ønsker en formel som gir riktig antall prikker for alle figurer.`,
    h`Antallet øker med 3 for hver ny figur: $$7-4=3$$, $$10-7=3$$ og $$13-10=3$$.`,
    h`Når økningen er 3, begynner vi med uttrykket $$3n$$.`,
    h`Prøv uttrykket i figur 1, altså $$n=1$$: $$3\cdot1=3$$.`,
    h`Figur 1 skal ha 4 prikker, men $$3n$$ gir bare 3. Vi mangler 1.`,
    h`Legg derfor til 1: $$P(n)=3n+1$$.`,
    h`Kontroll med figur 2: $$P(2)=3\cdot2+1=6+1=7$$. Det stemmer med mønsteret.`,
    h`Formelen er $$P(n)=3n+1$$.`,
  ],
  "m-04": [
    h`Bokstaven n står for figurnummeret. Vi vil finne en formel som gir antall ruter i figur n.`,
    h`Antallet øker med 4 hver gang: $$6-2=4$$, $$10-6=4$$ og $$14-10=4$$.`,
    h`Når økningen er 4, begynner vi med uttrykket $$4n$$.`,
    h`Prøv i figur 1: $$4\cdot1=4$$.`,
    h`Figur 1 skal ha 2 ruter, men $$4n$$ gir 4. Uttrykket er altså 2 for stort.`,
    h`Trekk derfor fra 2: $$R(n)=4n-2$$.`,
    h`Kontroll med figur 2: $$R(2)=4\cdot2-2=8-2=6$$. Det stemmer.`,
    h`Formelen er $$R(n)=4n-2$$.`,
  ],
  "m-05": [
    h`I formelen står n for figurnummeret. For figur 10 setter vi derfor $$n=10$$.`,
    h`Bytt ut n med 10: $$P(10)=3\cdot10+1$$.`,
    h`Regnerekkefølgen sier at gange skal regnes før pluss.`,
    h`Regn ut gangen: $$3\cdot10=30$$.`,
    h`Legg deretter til 1: $$30+1=31$$.`,
    h`Dermed er $$P(10)=31$$. Figur 10 har 31 prikker.`,
  ],
  "m-06": [
    h`I formelen står n for figurnummeret. For figur 10 bruker vi $$n=10$$.`,
    h`Bytt ut n med 10: $$R(10)=4\cdot10-2$$.`,
    h`Regnerekkefølgen sier at gange skal regnes før minus.`,
    h`Regn ut gangen: $$4\cdot10=40$$.`,
    h`Trekk deretter fra 2: $$40-2=38$$.`,
    h`Dermed er $$R(10)=38$$. Figur 10 har 38 ruter.`,
  ],
  "m-07": [
    h`Se om tallene kan skrives som et tall ganget med seg selv.`,
    h`$$1=1\cdot1=1^2$$ og $$4=2\cdot2=2^2$$.`,
    h`$$9=3\cdot3=3^2$$ og $$16=4\cdot4=4^2$$.`,
    h`Mønsteret viser at figurnummeret ganges med seg selv. Figur n har altså $$n^2$$ ruter.`,
    h`For figur 5 setter vi $$n=5$$. Da får vi $$5^2$$.`,
    h`$$5^2$$ betyr $$5\cdot5$$, og $$5\cdot5=25$$.`,
    h`Figur 5 har 25 ruter.`,
  ],
  "m-08": [
    h`Bokstaven n står for figurnummeret. Vi ser etter sammenhengen mellom figurnummeret og antall ruter.`,
    h`Figur 1 har 1 rute, og $$1=1\cdot1=1^2$$.`,
    h`Figur 2 har 4 ruter, og $$4=2\cdot2=2^2$$.`,
    h`Figur 3 har 9 ruter, og $$9=3\cdot3=3^2$$.`,
    h`Figur 4 har 16 ruter, og $$16=4\cdot4=4^2$$.`,
    h`Mønsteret er altså at figurnummeret ganges med seg selv.`,
    h`For figur n blir antallet $$n\cdot n=n^2$$.`,
    h`Formelen er $$R(n)=n^2$$.`,
  ],
  "m-09": [
    h`Vi leter etter figurnummeret n som gir 20 prikker. Sett derfor formelen lik 20: $$3n+2=20$$.`,
    h`Målet er å få n alene. På venstre side er 2 lagt til. Gjør det motsatte og trekk fra 2 på begge sider.`,
    h`Skriv $$3n+2-2=20-2$$.`,
    h`På venstre side forsvinner $$+2-2$$. På høyre side er $$20-2=18$$. Da får vi $$3n=18$$.`,
    h`Uttrykket $$3n$$ betyr $$3\cdot n$$. Del begge sider på 3.`,
    h`Da blir $$n=18:3$$.`,
    h`Siden $$18:3=6$$, er $$n=6$$.`,
    h`Kontroll: $$P(6)=3\cdot6+2=18+2=20$$. Det er figur nummer 6.`,
  ],
  "m-10": [
    h`Vi leter etter figurnummeret n som gir 27 ruter. Sett derfor formelen lik 27: $$4n-1=27$$.`,
    h`Målet er å få n alene. På venstre side er 1 trukket fra. Gjør det motsatte og legg til 1 på begge sider.`,
    h`Skriv $$4n-1+1=27+1$$.`,
    h`På venstre side forsvinner $$-1+1$$. På høyre side er $$27+1=28$$. Da får vi $$4n=28$$.`,
    h`Uttrykket $$4n$$ betyr $$4\cdot n$$. Del begge sider på 4.`,
    h`Da blir $$n=28:4$$.`,
    h`Siden $$28:4=7$$, er $$n=7$$.`,
    h`Kontroll: $$R(7)=4\cdot7-1=28-1=27$$. Det er figur nummer 7.`,
  ],
};

const ids = bank.oppgaver.map((oppgave) => oppgave.id);
const missing = ids.filter((id) => !hints[id]);
const unknown = Object.keys(hints).filter((id) => !ids.includes(id));

if (missing.length || unknown.length) {
  throw new Error(
    `Hintkartet passer ikke oppgavebanken. Mangler: ${missing.join(", ") || "ingen"}. Ukjente: ${unknown.join(", ") || "ingen"}.`,
  );
}

for (const oppgave of bank.oppgaver) {
  oppgave.hints = hints[oppgave.id];
}

bank.versjon = "2026.4";
fs.writeFileSync(file, `${JSON.stringify(bank, null, 2)}\n`);

const lengths = bank.oppgaver.map((oppgave) => oppgave.hints.length);
console.log(
  `Oppdatert ${bank.oppgaver.length} oppgaver med ${lengths.reduce((sum, count) => sum + count, 0)} hint.`,
);
console.log(`Hint per oppgave: ${Math.min(...lengths)}–${Math.max(...lengths)}.`);
